// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/account.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum clearmind.v1.ConnectionState
 */
export enum ConnectionState {
  /**
   * @generated from enum value: CONNECTION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONNECTION_STATE_DISCONNECTED = 1;
   */
  DISCONNECTED = 1,

  /**
   * @generated from enum value: CONNECTION_STATE_CONNECTED = 4;
   */
  CONNECTED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ConnectionState)
proto3.util.setEnumType(ConnectionState, "clearmind.v1.ConnectionState", [
  { no: 0, name: "CONNECTION_STATE_UNSPECIFIED" },
  { no: 1, name: "CONNECTION_STATE_DISCONNECTED" },
  { no: 4, name: "CONNECTION_STATE_CONNECTED" },
]);

/**
 * @generated from message clearmind.v1.AccountProfile
 */
export class AccountProfile extends Message<AccountProfile> {
  /**
   * @generated from field: int64 telegram_id = 1;
   */
  telegramId = protoInt64.zero;

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string display_name = 3;
   */
  displayName = "";

  /**
   * @generated from field: google.protobuf.Timestamp connected_at = 4;
   */
  connectedAt?: Timestamp;

  constructor(data?: PartialMessage<AccountProfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AccountProfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "telegram_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "connected_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountProfile {
    return new AccountProfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountProfile {
    return new AccountProfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountProfile {
    return new AccountProfile().fromJsonString(jsonString, options);
  }

  static equals(a: AccountProfile | PlainMessage<AccountProfile> | undefined, b: AccountProfile | PlainMessage<AccountProfile> | undefined): boolean {
    return proto3.util.equals(AccountProfile, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetStatusRequest
 */
export class GetStatusRequest extends Message<GetStatusRequest> {
  constructor(data?: PartialMessage<GetStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusRequest {
    return new GetStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined, b: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined): boolean {
    return proto3.util.equals(GetStatusRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetStatusResponse
 */
export class GetStatusResponse extends Message<GetStatusResponse> {
  /**
   * @generated from field: clearmind.v1.ConnectionState state = 1;
   */
  state = ConnectionState.UNSPECIFIED;

  /**
   * @generated from field: clearmind.v1.AccountProfile account = 2;
   */
  account?: AccountProfile;

  constructor(data?: PartialMessage<GetStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state", kind: "enum", T: proto3.getEnumType(ConnectionState) },
    { no: 2, name: "account", kind: "message", T: AccountProfile },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusResponse {
    return new GetStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined, b: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined): boolean {
    return proto3.util.equals(GetStatusResponse, a, b);
  }
}

