// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/account.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetStatusRequest, GetStatusResponse } from "./account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.AccountService
 */
export const AccountService = {
  typeName: "clearmind.v1.AccountService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.AccountService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

