// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/analysis_settings.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum clearmind.v1.AnalysisSchedule
 */
export enum AnalysisSchedule {
  /**
   * @generated from enum value: ANALYSIS_SCHEDULE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ANALYSIS_SCHEDULE_DAILY = 1;
   */
  DAILY = 1,

  /**
   * @generated from enum value: ANALYSIS_SCHEDULE_WEEKLY = 2;
   */
  WEEKLY = 2,

  /**
   * @generated from enum value: ANALYSIS_SCHEDULE_MANUAL = 3;
   */
  MANUAL = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(AnalysisSchedule)
proto3.util.setEnumType(AnalysisSchedule, "clearmind.v1.AnalysisSchedule", [
  { no: 0, name: "ANALYSIS_SCHEDULE_UNSPECIFIED" },
  { no: 1, name: "ANALYSIS_SCHEDULE_DAILY" },
  { no: 2, name: "ANALYSIS_SCHEDULE_WEEKLY" },
  { no: 3, name: "ANALYSIS_SCHEDULE_MANUAL" },
]);

/**
 * @generated from message clearmind.v1.SignalWeights
 */
export class SignalWeights extends Message<SignalWeights> {
  /**
   * @generated from field: double lexical = 1;
   */
  lexical = 0;

  /**
   * @generated from field: double links = 2;
   */
  links = 0;

  /**
   * @generated from field: double forwards = 3;
   */
  forwards = 0;

  /**
   * @generated from field: double timing = 4;
   */
  timing = 0;

  constructor(data?: PartialMessage<SignalWeights>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.SignalWeights";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "lexical", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "links", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "forwards", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "timing", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignalWeights {
    return new SignalWeights().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignalWeights {
    return new SignalWeights().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignalWeights {
    return new SignalWeights().fromJsonString(jsonString, options);
  }

  static equals(a: SignalWeights | PlainMessage<SignalWeights> | undefined, b: SignalWeights | PlainMessage<SignalWeights> | undefined): boolean {
    return proto3.util.equals(SignalWeights, a, b);
  }
}

/**
 * @generated from message clearmind.v1.AnalysisSettings
 */
export class AnalysisSettings extends Message<AnalysisSettings> {
  /**
   * @generated from field: int32 collection_window_days = 1;
   */
  collectionWindowDays = 0;

  /**
   * @generated from field: int32 min_posts_per_channel = 2;
   */
  minPostsPerChannel = 0;

  /**
   * @generated from field: int32 min_post_length = 3;
   */
  minPostLength = 0;

  /**
   * @generated from field: double duplicate_threshold = 4;
   */
  duplicateThreshold = 0;

  /**
   * @generated from field: double post_similarity_threshold = 5;
   */
  postSimilarityThreshold = 0;

  /**
   * @generated from field: int32 time_match_window_hours = 6;
   */
  timeMatchWindowHours = 0;

  /**
   * @generated from field: clearmind.v1.SignalWeights weights = 7;
   */
  weights?: SignalWeights;

  /**
   * @generated from field: int32 min_cluster_size = 8;
   */
  minClusterSize = 0;

  /**
   * @generated from field: double source_overlap_threshold = 9;
   */
  sourceOverlapThreshold = 0;

  /**
   * @generated from field: int32 recommendations_per_account = 10;
   */
  recommendationsPerAccount = 0;

  /**
   * @generated from field: double loss_warning_threshold = 11;
   */
  lossWarningThreshold = 0;

  /**
   * @generated from field: repeated string excluded_topics = 12;
   */
  excludedTopics: string[] = [];

  /**
   * @generated from field: clearmind.v1.AnalysisSchedule schedule = 13;
   */
  schedule = AnalysisSchedule.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 14;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: string updated_by_app_user_id = 15;
   */
  updatedByAppUserId = "";

  constructor(data?: PartialMessage<AnalysisSettings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AnalysisSettings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collection_window_days", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "min_posts_per_channel", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "min_post_length", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "duplicate_threshold", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "post_similarity_threshold", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "time_match_window_hours", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "weights", kind: "message", T: SignalWeights },
    { no: 8, name: "min_cluster_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "source_overlap_threshold", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 10, name: "recommendations_per_account", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "loss_warning_threshold", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 12, name: "excluded_topics", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 13, name: "schedule", kind: "enum", T: proto3.getEnumType(AnalysisSchedule) },
    { no: 14, name: "updated_at", kind: "message", T: Timestamp },
    { no: 15, name: "updated_by_app_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalysisSettings {
    return new AnalysisSettings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalysisSettings {
    return new AnalysisSettings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalysisSettings {
    return new AnalysisSettings().fromJsonString(jsonString, options);
  }

  static equals(a: AnalysisSettings | PlainMessage<AnalysisSettings> | undefined, b: AnalysisSettings | PlainMessage<AnalysisSettings> | undefined): boolean {
    return proto3.util.equals(AnalysisSettings, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetAnalysisSettingsRequest
 */
export class GetAnalysisSettingsRequest extends Message<GetAnalysisSettingsRequest> {
  constructor(data?: PartialMessage<GetAnalysisSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetAnalysisSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAnalysisSettingsRequest {
    return new GetAnalysisSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAnalysisSettingsRequest {
    return new GetAnalysisSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAnalysisSettingsRequest {
    return new GetAnalysisSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAnalysisSettingsRequest | PlainMessage<GetAnalysisSettingsRequest> | undefined, b: GetAnalysisSettingsRequest | PlainMessage<GetAnalysisSettingsRequest> | undefined): boolean {
    return proto3.util.equals(GetAnalysisSettingsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetAnalysisSettingsResponse
 */
export class GetAnalysisSettingsResponse extends Message<GetAnalysisSettingsResponse> {
  /**
   * @generated from field: clearmind.v1.AnalysisSettings settings = 1;
   */
  settings?: AnalysisSettings;

  constructor(data?: PartialMessage<GetAnalysisSettingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetAnalysisSettingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: AnalysisSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAnalysisSettingsResponse {
    return new GetAnalysisSettingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAnalysisSettingsResponse {
    return new GetAnalysisSettingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAnalysisSettingsResponse {
    return new GetAnalysisSettingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAnalysisSettingsResponse | PlainMessage<GetAnalysisSettingsResponse> | undefined, b: GetAnalysisSettingsResponse | PlainMessage<GetAnalysisSettingsResponse> | undefined): boolean {
    return proto3.util.equals(GetAnalysisSettingsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.UpdateAnalysisSettingsRequest
 */
export class UpdateAnalysisSettingsRequest extends Message<UpdateAnalysisSettingsRequest> {
  /**
   * @generated from field: clearmind.v1.AnalysisSettings settings = 1;
   */
  settings?: AnalysisSettings;

  constructor(data?: PartialMessage<UpdateAnalysisSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.UpdateAnalysisSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: AnalysisSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAnalysisSettingsRequest {
    return new UpdateAnalysisSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAnalysisSettingsRequest {
    return new UpdateAnalysisSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAnalysisSettingsRequest {
    return new UpdateAnalysisSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAnalysisSettingsRequest | PlainMessage<UpdateAnalysisSettingsRequest> | undefined, b: UpdateAnalysisSettingsRequest | PlainMessage<UpdateAnalysisSettingsRequest> | undefined): boolean {
    return proto3.util.equals(UpdateAnalysisSettingsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.UpdateAnalysisSettingsResponse
 */
export class UpdateAnalysisSettingsResponse extends Message<UpdateAnalysisSettingsResponse> {
  /**
   * @generated from field: clearmind.v1.AnalysisSettings settings = 1;
   */
  settings?: AnalysisSettings;

  constructor(data?: PartialMessage<UpdateAnalysisSettingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.UpdateAnalysisSettingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: AnalysisSettings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAnalysisSettingsResponse {
    return new UpdateAnalysisSettingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAnalysisSettingsResponse {
    return new UpdateAnalysisSettingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAnalysisSettingsResponse {
    return new UpdateAnalysisSettingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAnalysisSettingsResponse | PlainMessage<UpdateAnalysisSettingsResponse> | undefined, b: UpdateAnalysisSettingsResponse | PlainMessage<UpdateAnalysisSettingsResponse> | undefined): boolean {
    return proto3.util.equals(UpdateAnalysisSettingsResponse, a, b);
  }
}

