// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/analysis_settings.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAnalysisSettingsRequest, GetAnalysisSettingsResponse, UpdateAnalysisSettingsRequest, UpdateAnalysisSettingsResponse } from "./analysis_settings_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.AnalysisSettingsService
 */
export const AnalysisSettingsService = {
  typeName: "clearmind.v1.AnalysisSettingsService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.AnalysisSettingsService.GetAnalysisSettings
     */
    getAnalysisSettings: {
      name: "GetAnalysisSettings",
      I: GetAnalysisSettingsRequest,
      O: GetAnalysisSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.AnalysisSettingsService.UpdateAnalysisSettings
     */
    updateAnalysisSettings: {
      name: "UpdateAnalysisSettings",
      I: UpdateAnalysisSettingsRequest,
      O: UpdateAnalysisSettingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

