// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/auth.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAuthMethodsRequest, GetAuthMethodsResponse, GetCurrentUserRequest, GetCurrentUserResponse, GetUserRequest, GetUserResponse, LoginRequest, LoginResponse, LoginWithGoogleRequest, LoginWithGoogleResponse, LogoutRequest, LogoutResponse } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.AuthService
 */
export const AuthService = {
  typeName: "clearmind.v1.AuthService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.AuthService.LoginWithGoogle
     */
    loginWithGoogle: {
      name: "LoginWithGoogle",
      I: LoginWithGoogleRequest,
      O: LoginWithGoogleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.AuthService.GetAuthMethods
     */
    getAuthMethods: {
      name: "GetAuthMethods",
      I: GetAuthMethodsRequest,
      O: GetAuthMethodsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.AuthService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.AuthService.GetCurrentUser
     */
    getCurrentUser: {
      name: "GetCurrentUser",
      I: GetCurrentUserRequest,
      O: GetCurrentUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.AuthService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

