// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/channel.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { SocialMediaType } from "./common_pb.js";

/**
 * @generated from message clearmind.v1.Channel
 */
export class Channel extends Message<Channel> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: clearmind.v1.SocialMediaType social_media_type = 2;
   */
  socialMediaType = SocialMediaType.UNSPECIFIED;

  /**
   * @generated from field: string foreign_id = 3;
   */
  foreignId = "";

  /**
   * @generated from field: string username = 4;
   */
  username = "";

  /**
   * @generated from field: string title = 5;
   */
  title = "";

  constructor(data?: PartialMessage<Channel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.Channel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "social_media_type", kind: "enum", T: proto3.getEnumType(SocialMediaType) },
    { no: 3, name: "foreign_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Channel {
    return new Channel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Channel {
    return new Channel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Channel {
    return new Channel().fromJsonString(jsonString, options);
  }

  static equals(a: Channel | PlainMessage<Channel> | undefined, b: Channel | PlainMessage<Channel> | undefined): boolean {
    return proto3.util.equals(Channel, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ChannelProfile
 */
export class ChannelProfile extends Message<ChannelProfile> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: string snapshot_id = 4;
   */
  snapshotId = "";

  /**
   * @generated from field: int32 post_count = 5;
   */
  postCount = 0;

  /**
   * @generated from field: double posts_per_day = 6;
   */
  postsPerDay = 0;

  /**
   * @generated from field: double unique_content_share = 7;
   */
  uniqueContentShare = 0;

  /**
   * @generated from field: repeated clearmind.v1.DomainShare top_domains = 8;
   */
  topDomains: DomainShare[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp first_post_at = 9;
   */
  firstPostAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_post_at = 10;
   */
  lastPostAt?: Timestamp;

  constructor(data?: PartialMessage<ChannelProfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ChannelProfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "post_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "posts_per_day", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "unique_content_share", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "top_domains", kind: "message", T: DomainShare, repeated: true },
    { no: 9, name: "first_post_at", kind: "message", T: Timestamp },
    { no: 10, name: "last_post_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChannelProfile {
    return new ChannelProfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChannelProfile {
    return new ChannelProfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChannelProfile {
    return new ChannelProfile().fromJsonString(jsonString, options);
  }

  static equals(a: ChannelProfile | PlainMessage<ChannelProfile> | undefined, b: ChannelProfile | PlainMessage<ChannelProfile> | undefined): boolean {
    return proto3.util.equals(ChannelProfile, a, b);
  }
}

/**
 * @generated from message clearmind.v1.DomainShare
 */
export class DomainShare extends Message<DomainShare> {
  /**
   * @generated from field: string domain = 1;
   */
  domain = "";

  /**
   * @generated from field: double share = 2;
   */
  share = 0;

  /**
   * @generated from field: int32 post_count = 3;
   */
  postCount = 0;

  constructor(data?: PartialMessage<DomainShare>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.DomainShare";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "domain", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "share", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "post_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DomainShare {
    return new DomainShare().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DomainShare {
    return new DomainShare().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DomainShare {
    return new DomainShare().fromJsonString(jsonString, options);
  }

  static equals(a: DomainShare | PlainMessage<DomainShare> | undefined, b: DomainShare | PlainMessage<DomainShare> | undefined): boolean {
    return proto3.util.equals(DomainShare, a, b);
  }
}

