// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/channel_catalog.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddChannelRequest, AddChannelResponse, GetChannelRequest, GetChannelResponse, ImportChannelsFromSourceRequest, ImportChannelsFromSourceResponse, ListChannelAddedEventsRequest, ListChannelAddedEventsResponse, ListChannelsRequest, ListChannelsResponse, ListImportSourcesRequest, ListImportSourcesResponse, PauseChannelRequest, PauseChannelResponse, RemoveChannelRequest, RemoveChannelResponse, ResumeChannelRequest, ResumeChannelResponse } from "./channel_catalog_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.ChannelCatalogService
 */
export const ChannelCatalogService = {
  typeName: "clearmind.v1.ChannelCatalogService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.AddChannel
     */
    addChannel: {
      name: "AddChannel",
      I: AddChannelRequest,
      O: AddChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.ListChannels
     */
    listChannels: {
      name: "ListChannels",
      I: ListChannelsRequest,
      O: ListChannelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.GetChannel
     */
    getChannel: {
      name: "GetChannel",
      I: GetChannelRequest,
      O: GetChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.ListChannelAddedEvents
     */
    listChannelAddedEvents: {
      name: "ListChannelAddedEvents",
      I: ListChannelAddedEventsRequest,
      O: ListChannelAddedEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.PauseChannel
     */
    pauseChannel: {
      name: "PauseChannel",
      I: PauseChannelRequest,
      O: PauseChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.ResumeChannel
     */
    resumeChannel: {
      name: "ResumeChannel",
      I: ResumeChannelRequest,
      O: ResumeChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.RemoveChannel
     */
    removeChannel: {
      name: "RemoveChannel",
      I: RemoveChannelRequest,
      O: RemoveChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.ListImportSources
     */
    listImportSources: {
      name: "ListImportSources",
      I: ListImportSourcesRequest,
      O: ListImportSourcesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.ChannelCatalogService.ImportChannelsFromSource
     */
    importChannelsFromSource: {
      name: "ImportChannelsFromSource",
      I: ImportChannelsFromSourceRequest,
      O: ImportChannelsFromSourceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

