// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/channel_catalog.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Channel, ChannelProfile } from "./channel_pb.js";
import { PageRequest, PageResponse, SocialMediaType } from "./common_pb.js";

/**
 * @generated from enum clearmind.v1.ChannelStatus
 */
export enum ChannelStatus {
  /**
   * @generated from enum value: CHANNEL_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CHANNEL_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: CHANNEL_STATUS_PAUSED = 2;
   */
  PAUSED = 2,

  /**
   * @generated from enum value: CHANNEL_STATUS_ERROR = 3;
   */
  ERROR = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ChannelStatus)
proto3.util.setEnumType(ChannelStatus, "clearmind.v1.ChannelStatus", [
  { no: 0, name: "CHANNEL_STATUS_UNSPECIFIED" },
  { no: 1, name: "CHANNEL_STATUS_ACTIVE" },
  { no: 2, name: "CHANNEL_STATUS_PAUSED" },
  { no: 3, name: "CHANNEL_STATUS_ERROR" },
]);

/**
 * @generated from enum clearmind.v1.ChannelAddedSource
 */
export enum ChannelAddedSource {
  /**
   * @generated from enum value: CHANNEL_ADDED_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CHANNEL_ADDED_SOURCE_IMPORT = 1;
   */
  IMPORT = 1,

  /**
   * @generated from enum value: CHANNEL_ADDED_SOURCE_MANUAL = 2;
   */
  MANUAL = 2,

  /**
   * @generated from enum value: CHANNEL_ADDED_SOURCE_EXTERNAL = 3;
   */
  EXTERNAL = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ChannelAddedSource)
proto3.util.setEnumType(ChannelAddedSource, "clearmind.v1.ChannelAddedSource", [
  { no: 0, name: "CHANNEL_ADDED_SOURCE_UNSPECIFIED" },
  { no: 1, name: "CHANNEL_ADDED_SOURCE_IMPORT" },
  { no: 2, name: "CHANNEL_ADDED_SOURCE_MANUAL" },
  { no: 3, name: "CHANNEL_ADDED_SOURCE_EXTERNAL" },
]);

/**
 * @generated from enum clearmind.v1.ImportChannelOutcome
 */
export enum ImportChannelOutcome {
  /**
   * @generated from enum value: IMPORT_CHANNEL_OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: IMPORT_CHANNEL_OUTCOME_ADDED = 1;
   */
  ADDED = 1,

  /**
   * @generated from enum value: IMPORT_CHANNEL_OUTCOME_ALREADY_PRESENT = 2;
   */
  ALREADY_PRESENT = 2,

  /**
   * @generated from enum value: IMPORT_CHANNEL_OUTCOME_REJECTED_GROUP = 3;
   */
  REJECTED_GROUP = 3,

  /**
   * @generated from enum value: IMPORT_CHANNEL_OUTCOME_REJECTED_UNRESOLVED = 4;
   */
  REJECTED_UNRESOLVED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ImportChannelOutcome)
proto3.util.setEnumType(ImportChannelOutcome, "clearmind.v1.ImportChannelOutcome", [
  { no: 0, name: "IMPORT_CHANNEL_OUTCOME_UNSPECIFIED" },
  { no: 1, name: "IMPORT_CHANNEL_OUTCOME_ADDED" },
  { no: 2, name: "IMPORT_CHANNEL_OUTCOME_ALREADY_PRESENT" },
  { no: 3, name: "IMPORT_CHANNEL_OUTCOME_REJECTED_GROUP" },
  { no: 4, name: "IMPORT_CHANNEL_OUTCOME_REJECTED_UNRESOLVED" },
]);

/**
 * @generated from message clearmind.v1.CatalogChannel
 */
export class CatalogChannel extends Message<CatalogChannel> {
  /**
   * @generated from field: clearmind.v1.Channel channel = 1;
   */
  channel?: Channel;

  /**
   * @generated from field: google.protobuf.Timestamp added_at = 2;
   */
  addedAt?: Timestamp;

  /**
   * @generated from field: bool has_profile = 3;
   */
  hasProfile = false;

  /**
   * @generated from field: clearmind.v1.ChannelProfile profile = 4;
   */
  profile?: ChannelProfile;

  /**
   * @generated from field: clearmind.v1.ChannelStatus status = 5;
   */
  status = ChannelStatus.UNSPECIFIED;

  constructor(data?: PartialMessage<CatalogChannel>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.CatalogChannel";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel", kind: "message", T: Channel },
    { no: 2, name: "added_at", kind: "message", T: Timestamp },
    { no: 3, name: "has_profile", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "profile", kind: "message", T: ChannelProfile },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(ChannelStatus) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CatalogChannel {
    return new CatalogChannel().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CatalogChannel {
    return new CatalogChannel().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CatalogChannel {
    return new CatalogChannel().fromJsonString(jsonString, options);
  }

  static equals(a: CatalogChannel | PlainMessage<CatalogChannel> | undefined, b: CatalogChannel | PlainMessage<CatalogChannel> | undefined): boolean {
    return proto3.util.equals(CatalogChannel, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ChannelAddedEvent
 */
export class ChannelAddedEvent extends Message<ChannelAddedEvent> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string channel_id = 2;
   */
  channelId = "";

  /**
   * @generated from field: clearmind.v1.ChannelAddedSource source = 3;
   */
  source = ChannelAddedSource.UNSPECIFIED;

  /**
   * @generated from field: string app_user_id = 4;
   */
  appUserId = "";

  /**
   * @generated from field: string app_username = 5;
   */
  appUsername = "";

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 6;
   */
  occurredAt?: Timestamp;

  /**
   * @generated from field: string import_source = 7;
   */
  importSource = "";

  constructor(data?: PartialMessage<ChannelAddedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ChannelAddedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "source", kind: "enum", T: proto3.getEnumType(ChannelAddedSource) },
    { no: 4, name: "app_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "app_username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "occurred_at", kind: "message", T: Timestamp },
    { no: 7, name: "import_source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChannelAddedEvent {
    return new ChannelAddedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChannelAddedEvent {
    return new ChannelAddedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChannelAddedEvent {
    return new ChannelAddedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: ChannelAddedEvent | PlainMessage<ChannelAddedEvent> | undefined, b: ChannelAddedEvent | PlainMessage<ChannelAddedEvent> | undefined): boolean {
    return proto3.util.equals(ChannelAddedEvent, a, b);
  }
}

/**
 * @generated from message clearmind.v1.AddChannelRequest
 */
export class AddChannelRequest extends Message<AddChannelRequest> {
  /**
   * @generated from field: clearmind.v1.SocialMediaType social_media_type = 1;
   */
  socialMediaType = SocialMediaType.UNSPECIFIED;

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string foreign_id = 3;
   */
  foreignId = "";

  constructor(data?: PartialMessage<AddChannelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AddChannelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "social_media_type", kind: "enum", T: proto3.getEnumType(SocialMediaType) },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "foreign_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddChannelRequest {
    return new AddChannelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddChannelRequest {
    return new AddChannelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddChannelRequest {
    return new AddChannelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddChannelRequest | PlainMessage<AddChannelRequest> | undefined, b: AddChannelRequest | PlainMessage<AddChannelRequest> | undefined): boolean {
    return proto3.util.equals(AddChannelRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.AddChannelResponse
 */
export class AddChannelResponse extends Message<AddChannelResponse> {
  /**
   * @generated from field: clearmind.v1.CatalogChannel channel = 1;
   */
  channel?: CatalogChannel;

  constructor(data?: PartialMessage<AddChannelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AddChannelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel", kind: "message", T: CatalogChannel },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddChannelResponse {
    return new AddChannelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddChannelResponse {
    return new AddChannelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddChannelResponse {
    return new AddChannelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AddChannelResponse | PlainMessage<AddChannelResponse> | undefined, b: AddChannelResponse | PlainMessage<AddChannelResponse> | undefined): boolean {
    return proto3.util.equals(AddChannelResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListChannelsRequest
 */
export class ListChannelsRequest extends Message<ListChannelsRequest> {
  /**
   * @generated from field: clearmind.v1.PageRequest page = 1;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListChannelsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListChannelsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListChannelsRequest {
    return new ListChannelsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListChannelsRequest {
    return new ListChannelsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListChannelsRequest {
    return new ListChannelsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListChannelsRequest | PlainMessage<ListChannelsRequest> | undefined, b: ListChannelsRequest | PlainMessage<ListChannelsRequest> | undefined): boolean {
    return proto3.util.equals(ListChannelsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListChannelsResponse
 */
export class ListChannelsResponse extends Message<ListChannelsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.CatalogChannel channels = 1;
   */
  channels: CatalogChannel[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListChannelsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListChannelsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channels", kind: "message", T: CatalogChannel, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListChannelsResponse {
    return new ListChannelsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListChannelsResponse {
    return new ListChannelsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListChannelsResponse {
    return new ListChannelsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListChannelsResponse | PlainMessage<ListChannelsResponse> | undefined, b: ListChannelsResponse | PlainMessage<ListChannelsResponse> | undefined): boolean {
    return proto3.util.equals(ListChannelsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetChannelRequest
 */
export class GetChannelRequest extends Message<GetChannelRequest> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  constructor(data?: PartialMessage<GetChannelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetChannelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChannelRequest {
    return new GetChannelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChannelRequest {
    return new GetChannelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChannelRequest {
    return new GetChannelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetChannelRequest | PlainMessage<GetChannelRequest> | undefined, b: GetChannelRequest | PlainMessage<GetChannelRequest> | undefined): boolean {
    return proto3.util.equals(GetChannelRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetChannelResponse
 */
export class GetChannelResponse extends Message<GetChannelResponse> {
  /**
   * @generated from field: clearmind.v1.CatalogChannel channel = 1;
   */
  channel?: CatalogChannel;

  constructor(data?: PartialMessage<GetChannelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetChannelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel", kind: "message", T: CatalogChannel },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetChannelResponse {
    return new GetChannelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetChannelResponse {
    return new GetChannelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetChannelResponse {
    return new GetChannelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetChannelResponse | PlainMessage<GetChannelResponse> | undefined, b: GetChannelResponse | PlainMessage<GetChannelResponse> | undefined): boolean {
    return proto3.util.equals(GetChannelResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListChannelAddedEventsRequest
 */
export class ListChannelAddedEventsRequest extends Message<ListChannelAddedEventsRequest> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: clearmind.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListChannelAddedEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListChannelAddedEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListChannelAddedEventsRequest {
    return new ListChannelAddedEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListChannelAddedEventsRequest {
    return new ListChannelAddedEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListChannelAddedEventsRequest {
    return new ListChannelAddedEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListChannelAddedEventsRequest | PlainMessage<ListChannelAddedEventsRequest> | undefined, b: ListChannelAddedEventsRequest | PlainMessage<ListChannelAddedEventsRequest> | undefined): boolean {
    return proto3.util.equals(ListChannelAddedEventsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListChannelAddedEventsResponse
 */
export class ListChannelAddedEventsResponse extends Message<ListChannelAddedEventsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.ChannelAddedEvent events = 1;
   */
  events: ChannelAddedEvent[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListChannelAddedEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListChannelAddedEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: ChannelAddedEvent, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListChannelAddedEventsResponse {
    return new ListChannelAddedEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListChannelAddedEventsResponse {
    return new ListChannelAddedEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListChannelAddedEventsResponse {
    return new ListChannelAddedEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListChannelAddedEventsResponse | PlainMessage<ListChannelAddedEventsResponse> | undefined, b: ListChannelAddedEventsResponse | PlainMessage<ListChannelAddedEventsResponse> | undefined): boolean {
    return proto3.util.equals(ListChannelAddedEventsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.PauseChannelRequest
 */
export class PauseChannelRequest extends Message<PauseChannelRequest> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  constructor(data?: PartialMessage<PauseChannelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.PauseChannelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PauseChannelRequest {
    return new PauseChannelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PauseChannelRequest {
    return new PauseChannelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PauseChannelRequest {
    return new PauseChannelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PauseChannelRequest | PlainMessage<PauseChannelRequest> | undefined, b: PauseChannelRequest | PlainMessage<PauseChannelRequest> | undefined): boolean {
    return proto3.util.equals(PauseChannelRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.PauseChannelResponse
 */
export class PauseChannelResponse extends Message<PauseChannelResponse> {
  /**
   * @generated from field: clearmind.v1.CatalogChannel channel = 1;
   */
  channel?: CatalogChannel;

  constructor(data?: PartialMessage<PauseChannelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.PauseChannelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel", kind: "message", T: CatalogChannel },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PauseChannelResponse {
    return new PauseChannelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PauseChannelResponse {
    return new PauseChannelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PauseChannelResponse {
    return new PauseChannelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PauseChannelResponse | PlainMessage<PauseChannelResponse> | undefined, b: PauseChannelResponse | PlainMessage<PauseChannelResponse> | undefined): boolean {
    return proto3.util.equals(PauseChannelResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ResumeChannelRequest
 */
export class ResumeChannelRequest extends Message<ResumeChannelRequest> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  constructor(data?: PartialMessage<ResumeChannelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ResumeChannelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResumeChannelRequest {
    return new ResumeChannelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResumeChannelRequest {
    return new ResumeChannelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResumeChannelRequest {
    return new ResumeChannelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResumeChannelRequest | PlainMessage<ResumeChannelRequest> | undefined, b: ResumeChannelRequest | PlainMessage<ResumeChannelRequest> | undefined): boolean {
    return proto3.util.equals(ResumeChannelRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ResumeChannelResponse
 */
export class ResumeChannelResponse extends Message<ResumeChannelResponse> {
  /**
   * @generated from field: clearmind.v1.CatalogChannel channel = 1;
   */
  channel?: CatalogChannel;

  constructor(data?: PartialMessage<ResumeChannelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ResumeChannelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel", kind: "message", T: CatalogChannel },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResumeChannelResponse {
    return new ResumeChannelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResumeChannelResponse {
    return new ResumeChannelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResumeChannelResponse {
    return new ResumeChannelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ResumeChannelResponse | PlainMessage<ResumeChannelResponse> | undefined, b: ResumeChannelResponse | PlainMessage<ResumeChannelResponse> | undefined): boolean {
    return proto3.util.equals(ResumeChannelResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.RemoveChannelRequest
 */
export class RemoveChannelRequest extends Message<RemoveChannelRequest> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: string username_confirmation = 2;
   */
  usernameConfirmation = "";

  /**
   * @generated from field: bool retain_posts = 3;
   */
  retainPosts = false;

  constructor(data?: PartialMessage<RemoveChannelRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.RemoveChannelRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username_confirmation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "retain_posts", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveChannelRequest {
    return new RemoveChannelRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveChannelRequest {
    return new RemoveChannelRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveChannelRequest {
    return new RemoveChannelRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveChannelRequest | PlainMessage<RemoveChannelRequest> | undefined, b: RemoveChannelRequest | PlainMessage<RemoveChannelRequest> | undefined): boolean {
    return proto3.util.equals(RemoveChannelRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.RemoveChannelResponse
 */
export class RemoveChannelResponse extends Message<RemoveChannelResponse> {
  /**
   * @generated from field: google.protobuf.Timestamp posts_retained_until = 1;
   */
  postsRetainedUntil?: Timestamp;

  constructor(data?: PartialMessage<RemoveChannelResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.RemoveChannelResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "posts_retained_until", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveChannelResponse {
    return new RemoveChannelResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveChannelResponse {
    return new RemoveChannelResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveChannelResponse {
    return new RemoveChannelResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveChannelResponse | PlainMessage<RemoveChannelResponse> | undefined, b: RemoveChannelResponse | PlainMessage<RemoveChannelResponse> | undefined): boolean {
    return proto3.util.equals(RemoveChannelResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ImportSource
 */
export class ImportSource extends Message<ImportSource> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: clearmind.v1.SocialMediaType social_media_type = 2;
   */
  socialMediaType = SocialMediaType.UNSPECIFIED;

  /**
   * @generated from field: bool available = 3;
   */
  available = false;

  constructor(data?: PartialMessage<ImportSource>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ImportSource";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "social_media_type", kind: "enum", T: proto3.getEnumType(SocialMediaType) },
    { no: 3, name: "available", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportSource {
    return new ImportSource().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportSource {
    return new ImportSource().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportSource {
    return new ImportSource().fromJsonString(jsonString, options);
  }

  static equals(a: ImportSource | PlainMessage<ImportSource> | undefined, b: ImportSource | PlainMessage<ImportSource> | undefined): boolean {
    return proto3.util.equals(ImportSource, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListImportSourcesRequest
 */
export class ListImportSourcesRequest extends Message<ListImportSourcesRequest> {
  constructor(data?: PartialMessage<ListImportSourcesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListImportSourcesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListImportSourcesRequest {
    return new ListImportSourcesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListImportSourcesRequest {
    return new ListImportSourcesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListImportSourcesRequest {
    return new ListImportSourcesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListImportSourcesRequest | PlainMessage<ListImportSourcesRequest> | undefined, b: ListImportSourcesRequest | PlainMessage<ListImportSourcesRequest> | undefined): boolean {
    return proto3.util.equals(ListImportSourcesRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListImportSourcesResponse
 */
export class ListImportSourcesResponse extends Message<ListImportSourcesResponse> {
  /**
   * @generated from field: repeated clearmind.v1.ImportSource sources = 1;
   */
  sources: ImportSource[] = [];

  constructor(data?: PartialMessage<ListImportSourcesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListImportSourcesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sources", kind: "message", T: ImportSource, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListImportSourcesResponse {
    return new ListImportSourcesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListImportSourcesResponse {
    return new ListImportSourcesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListImportSourcesResponse {
    return new ListImportSourcesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListImportSourcesResponse | PlainMessage<ListImportSourcesResponse> | undefined, b: ListImportSourcesResponse | PlainMessage<ListImportSourcesResponse> | undefined): boolean {
    return proto3.util.equals(ListImportSourcesResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ImportChannelResult
 */
export class ImportChannelResult extends Message<ImportChannelResult> {
  /**
   * @generated from field: string username = 1;
   */
  username = "";

  /**
   * @generated from field: clearmind.v1.ImportChannelOutcome outcome = 2;
   */
  outcome = ImportChannelOutcome.UNSPECIFIED;

  /**
   * @generated from field: string channel_id = 3;
   */
  channelId = "";

  constructor(data?: PartialMessage<ImportChannelResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ImportChannelResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "outcome", kind: "enum", T: proto3.getEnumType(ImportChannelOutcome) },
    { no: 3, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportChannelResult {
    return new ImportChannelResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportChannelResult {
    return new ImportChannelResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportChannelResult {
    return new ImportChannelResult().fromJsonString(jsonString, options);
  }

  static equals(a: ImportChannelResult | PlainMessage<ImportChannelResult> | undefined, b: ImportChannelResult | PlainMessage<ImportChannelResult> | undefined): boolean {
    return proto3.util.equals(ImportChannelResult, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ImportChannelsFromSourceRequest
 */
export class ImportChannelsFromSourceRequest extends Message<ImportChannelsFromSourceRequest> {
  /**
   * @generated from field: string source = 1;
   */
  source = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<ImportChannelsFromSourceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ImportChannelsFromSourceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportChannelsFromSourceRequest {
    return new ImportChannelsFromSourceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportChannelsFromSourceRequest {
    return new ImportChannelsFromSourceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportChannelsFromSourceRequest {
    return new ImportChannelsFromSourceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ImportChannelsFromSourceRequest | PlainMessage<ImportChannelsFromSourceRequest> | undefined, b: ImportChannelsFromSourceRequest | PlainMessage<ImportChannelsFromSourceRequest> | undefined): boolean {
    return proto3.util.equals(ImportChannelsFromSourceRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ImportChannelsFromSourceResponse
 */
export class ImportChannelsFromSourceResponse extends Message<ImportChannelsFromSourceResponse> {
  /**
   * @generated from field: repeated clearmind.v1.ImportChannelResult results = 1;
   */
  results: ImportChannelResult[] = [];

  constructor(data?: PartialMessage<ImportChannelsFromSourceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ImportChannelsFromSourceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "results", kind: "message", T: ImportChannelResult, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportChannelsFromSourceResponse {
    return new ImportChannelsFromSourceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportChannelsFromSourceResponse {
    return new ImportChannelsFromSourceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportChannelsFromSourceResponse {
    return new ImportChannelsFromSourceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ImportChannelsFromSourceResponse | PlainMessage<ImportChannelsFromSourceResponse> | undefined, b: ImportChannelsFromSourceResponse | PlainMessage<ImportChannelsFromSourceResponse> | undefined): boolean {
    return proto3.util.equals(ImportChannelsFromSourceResponse, a, b);
  }
}

