// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/common.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum clearmind.v1.SocialMediaType
 */
export enum SocialMediaType {
  /**
   * @generated from enum value: SOCIAL_MEDIA_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SOCIAL_MEDIA_TYPE_TELEGRAM = 1;
   */
  TELEGRAM = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(SocialMediaType)
proto3.util.setEnumType(SocialMediaType, "clearmind.v1.SocialMediaType", [
  { no: 0, name: "SOCIAL_MEDIA_TYPE_UNSPECIFIED" },
  { no: 1, name: "SOCIAL_MEDIA_TYPE_TELEGRAM" },
]);

/**
 * @generated from enum clearmind.v1.RunStatus
 */
export enum RunStatus {
  /**
   * @generated from enum value: RUN_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RUN_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: RUN_STATUS_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * @generated from enum value: RUN_STATUS_SUCCEEDED = 3;
   */
  SUCCEEDED = 3,

  /**
   * @generated from enum value: RUN_STATUS_PARTIAL = 4;
   */
  PARTIAL = 4,

  /**
   * @generated from enum value: RUN_STATUS_FAILED = 5;
   */
  FAILED = 5,

  /**
   * @generated from enum value: RUN_STATUS_CANCELLED = 6;
   */
  CANCELLED = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(RunStatus)
proto3.util.setEnumType(RunStatus, "clearmind.v1.RunStatus", [
  { no: 0, name: "RUN_STATUS_UNSPECIFIED" },
  { no: 1, name: "RUN_STATUS_PENDING" },
  { no: 2, name: "RUN_STATUS_RUNNING" },
  { no: 3, name: "RUN_STATUS_SUCCEEDED" },
  { no: 4, name: "RUN_STATUS_PARTIAL" },
  { no: 5, name: "RUN_STATUS_FAILED" },
  { no: 6, name: "RUN_STATUS_CANCELLED" },
]);

/**
 * @generated from enum clearmind.v1.RunFailureCode
 */
export enum RunFailureCode {
  /**
   * @generated from enum value: RUN_FAILURE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RUN_FAILURE_CODE_ACCOUNT_NOT_CONNECTED = 1;
   */
  ACCOUNT_NOT_CONNECTED = 1,

  /**
   * @generated from enum value: RUN_FAILURE_CODE_PLATFORM_UNAVAILABLE = 2;
   */
  PLATFORM_UNAVAILABLE = 2,

  /**
   * @generated from enum value: RUN_FAILURE_CODE_COLLECTION_UNUSABLE = 3;
   */
  COLLECTION_UNUSABLE = 3,

  /**
   * @generated from enum value: RUN_FAILURE_CODE_COLLECTION_WAIT_EXCEEDED = 4;
   */
  COLLECTION_WAIT_EXCEEDED = 4,

  /**
   * @generated from enum value: RUN_FAILURE_CODE_INTERNAL = 5;
   */
  INTERNAL = 5,

  /**
   * @generated from enum value: RUN_FAILURE_CODE_CHANNELS_FAILED = 6;
   */
  CHANNELS_FAILED = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(RunFailureCode)
proto3.util.setEnumType(RunFailureCode, "clearmind.v1.RunFailureCode", [
  { no: 0, name: "RUN_FAILURE_CODE_UNSPECIFIED" },
  { no: 1, name: "RUN_FAILURE_CODE_ACCOUNT_NOT_CONNECTED" },
  { no: 2, name: "RUN_FAILURE_CODE_PLATFORM_UNAVAILABLE" },
  { no: 3, name: "RUN_FAILURE_CODE_COLLECTION_UNUSABLE" },
  { no: 4, name: "RUN_FAILURE_CODE_COLLECTION_WAIT_EXCEEDED" },
  { no: 5, name: "RUN_FAILURE_CODE_INTERNAL" },
  { no: 6, name: "RUN_FAILURE_CODE_CHANNELS_FAILED" },
]);

/**
 * @generated from message clearmind.v1.PageRequest
 */
export class PageRequest extends Message<PageRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  constructor(data?: PartialMessage<PageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.PageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageRequest {
    return new PageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageRequest {
    return new PageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageRequest {
    return new PageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PageRequest | PlainMessage<PageRequest> | undefined, b: PageRequest | PlainMessage<PageRequest> | undefined): boolean {
    return proto3.util.equals(PageRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.PageResponse
 */
export class PageResponse extends Message<PageResponse> {
  /**
   * @generated from field: string next_page_token = 1;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<PageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.PageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageResponse {
    return new PageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageResponse {
    return new PageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageResponse {
    return new PageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PageResponse | PlainMessage<PageResponse> | undefined, b: PageResponse | PlainMessage<PageResponse> | undefined): boolean {
    return proto3.util.equals(PageResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.TimeWindow
 */
export class TimeWindow extends Message<TimeWindow> {
  /**
   * @generated from field: google.protobuf.Timestamp from_time = 1;
   */
  fromTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp to_time = 2;
   */
  toTime?: Timestamp;

  constructor(data?: PartialMessage<TimeWindow>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.TimeWindow";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from_time", kind: "message", T: Timestamp },
    { no: 2, name: "to_time", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimeWindow {
    return new TimeWindow().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimeWindow {
    return new TimeWindow().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimeWindow {
    return new TimeWindow().fromJsonString(jsonString, options);
  }

  static equals(a: TimeWindow | PlainMessage<TimeWindow> | undefined, b: TimeWindow | PlainMessage<TimeWindow> | undefined): boolean {
    return proto3.util.equals(TimeWindow, a, b);
  }
}

/**
 * @generated from message clearmind.v1.RunFailure
 */
export class RunFailure extends Message<RunFailure> {
  /**
   * @generated from field: clearmind.v1.RunFailureCode code = 1;
   */
  code = RunFailureCode.UNSPECIFIED;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<RunFailure>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.RunFailure";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "enum", T: proto3.getEnumType(RunFailureCode) },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunFailure {
    return new RunFailure().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunFailure {
    return new RunFailure().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunFailure {
    return new RunFailure().fromJsonString(jsonString, options);
  }

  static equals(a: RunFailure | PlainMessage<RunFailure> | undefined, b: RunFailure | PlainMessage<RunFailure> | undefined): boolean {
    return proto3.util.equals(RunFailure, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ChannelError
 */
export class ChannelError extends Message<ChannelError> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: string channel_username = 2;
   */
  channelUsername = "";

  /**
   * @generated from field: string message = 3;
   */
  message = "";

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 4;
   */
  occurredAt?: Timestamp;

  constructor(data?: PartialMessage<ChannelError>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ChannelError";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "channel_username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "occurred_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChannelError {
    return new ChannelError().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChannelError {
    return new ChannelError().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChannelError {
    return new ChannelError().fromJsonString(jsonString, options);
  }

  static equals(a: ChannelError | PlainMessage<ChannelError> | undefined, b: ChannelError | PlainMessage<ChannelError> | undefined): boolean {
    return proto3.util.equals(ChannelError, a, b);
  }
}

