// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/duplication.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { ChannelError, PageRequest, PageResponse, RunFailure, RunStatus } from "./common_pb.js";

/**
 * @generated from enum clearmind.v1.MatchVerdict
 */
export enum MatchVerdict {
  /**
   * @generated from enum value: MATCH_VERDICT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MATCH_VERDICT_DUPLICATE = 1;
   */
  DUPLICATE = 1,

  /**
   * @generated from enum value: MATCH_VERDICT_NOT_DUPLICATE = 2;
   */
  NOT_DUPLICATE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(MatchVerdict)
proto3.util.setEnumType(MatchVerdict, "clearmind.v1.MatchVerdict", [
  { no: 0, name: "MATCH_VERDICT_UNSPECIFIED" },
  { no: 1, name: "MATCH_VERDICT_DUPLICATE" },
  { no: 2, name: "MATCH_VERDICT_NOT_DUPLICATE" },
]);

/**
 * @generated from enum clearmind.v1.MatchEventKind
 */
export enum MatchEventKind {
  /**
   * @generated from enum value: MATCH_EVENT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MATCH_EVENT_KIND_MARKED_DUPLICATE = 1;
   */
  MARKED_DUPLICATE = 1,

  /**
   * @generated from enum value: MATCH_EVENT_KIND_MARKED_NOT_DUPLICATE = 2;
   */
  MARKED_NOT_DUPLICATE = 2,

  /**
   * @generated from enum value: MATCH_EVENT_KIND_RESET = 3;
   */
  RESET = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(MatchEventKind)
proto3.util.setEnumType(MatchEventKind, "clearmind.v1.MatchEventKind", [
  { no: 0, name: "MATCH_EVENT_KIND_UNSPECIFIED" },
  { no: 1, name: "MATCH_EVENT_KIND_MARKED_DUPLICATE" },
  { no: 2, name: "MATCH_EVENT_KIND_MARKED_NOT_DUPLICATE" },
  { no: 3, name: "MATCH_EVENT_KIND_RESET" },
]);

/**
 * @generated from enum clearmind.v1.RelationKind
 */
export enum RelationKind {
  /**
   * @generated from enum value: RELATION_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RELATION_KIND_PERSISTENT_DUPLICATION = 1;
   */
  PERSISTENT_DUPLICATION = 1,

  /**
   * @generated from enum value: RELATION_KIND_PARTIAL_OVERLAP = 2;
   */
  PARTIAL_OVERLAP = 2,

  /**
   * @generated from enum value: RELATION_KIND_SOURCE_OVERLAP = 3;
   */
  SOURCE_OVERLAP = 3,

  /**
   * @generated from enum value: RELATION_KIND_INDEPENDENT = 4;
   */
  INDEPENDENT = 4,

  /**
   * @generated from enum value: RELATION_KIND_INSUFFICIENT_DATA = 5;
   */
  INSUFFICIENT_DATA = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(RelationKind)
proto3.util.setEnumType(RelationKind, "clearmind.v1.RelationKind", [
  { no: 0, name: "RELATION_KIND_UNSPECIFIED" },
  { no: 1, name: "RELATION_KIND_PERSISTENT_DUPLICATION" },
  { no: 2, name: "RELATION_KIND_PARTIAL_OVERLAP" },
  { no: 3, name: "RELATION_KIND_SOURCE_OVERLAP" },
  { no: 4, name: "RELATION_KIND_INDEPENDENT" },
  { no: 5, name: "RELATION_KIND_INSUFFICIENT_DATA" },
]);

/**
 * @generated from enum clearmind.v1.SignalKind
 */
export enum SignalKind {
  /**
   * @generated from enum value: SIGNAL_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SIGNAL_KIND_LEXICAL_OVERLAP = 1;
   */
  LEXICAL_OVERLAP = 1,

  /**
   * @generated from enum value: SIGNAL_KIND_SEMANTIC_PROXIMITY = 2;
   */
  SEMANTIC_PROXIMITY = 2,

  /**
   * @generated from enum value: SIGNAL_KIND_SHARED_LINKS = 3;
   */
  SHARED_LINKS = 3,

  /**
   * @generated from enum value: SIGNAL_KIND_SHARED_DOMAINS = 4;
   */
  SHARED_DOMAINS = 4,

  /**
   * @generated from enum value: SIGNAL_KIND_FORWARD = 5;
   */
  FORWARD = 5,

  /**
   * @generated from enum value: SIGNAL_KIND_TIMING = 6;
   */
  TIMING = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(SignalKind)
proto3.util.setEnumType(SignalKind, "clearmind.v1.SignalKind", [
  { no: 0, name: "SIGNAL_KIND_UNSPECIFIED" },
  { no: 1, name: "SIGNAL_KIND_LEXICAL_OVERLAP" },
  { no: 2, name: "SIGNAL_KIND_SEMANTIC_PROXIMITY" },
  { no: 3, name: "SIGNAL_KIND_SHARED_LINKS" },
  { no: 4, name: "SIGNAL_KIND_SHARED_DOMAINS" },
  { no: 5, name: "SIGNAL_KIND_FORWARD" },
  { no: 6, name: "SIGNAL_KIND_TIMING" },
]);

/**
 * @generated from enum clearmind.v1.AnalysisStage
 */
export enum AnalysisStage {
  /**
   * @generated from enum value: ANALYSIS_STAGE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ANALYSIS_STAGE_LOADING_POSTS = 1;
   */
  LOADING_POSTS = 1,

  /**
   * @generated from enum value: ANALYSIS_STAGE_SIGNATURES = 2;
   */
  SIGNATURES = 2,

  /**
   * @generated from enum value: ANALYSIS_STAGE_PAIR_COMPARISON = 3;
   */
  PAIR_COMPARISON = 3,

  /**
   * @generated from enum value: ANALYSIS_STAGE_RECOMMENDATIONS = 4;
   */
  RECOMMENDATIONS = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(AnalysisStage)
proto3.util.setEnumType(AnalysisStage, "clearmind.v1.AnalysisStage", [
  { no: 0, name: "ANALYSIS_STAGE_UNSPECIFIED" },
  { no: 1, name: "ANALYSIS_STAGE_LOADING_POSTS" },
  { no: 2, name: "ANALYSIS_STAGE_SIGNATURES" },
  { no: 3, name: "ANALYSIS_STAGE_PAIR_COMPARISON" },
  { no: 4, name: "ANALYSIS_STAGE_RECOMMENDATIONS" },
]);

/**
 * @generated from enum clearmind.v1.AnalysisTrigger
 */
export enum AnalysisTrigger {
  /**
   * @generated from enum value: ANALYSIS_TRIGGER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ANALYSIS_TRIGGER_MANUAL = 1;
   */
  MANUAL = 1,

  /**
   * @generated from enum value: ANALYSIS_TRIGGER_AFTER_INGESTION = 2;
   */
  AFTER_INGESTION = 2,

  /**
   * @generated from enum value: ANALYSIS_TRIGGER_SCHEDULE = 3;
   */
  SCHEDULE = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(AnalysisTrigger)
proto3.util.setEnumType(AnalysisTrigger, "clearmind.v1.AnalysisTrigger", [
  { no: 0, name: "ANALYSIS_TRIGGER_UNSPECIFIED" },
  { no: 1, name: "ANALYSIS_TRIGGER_MANUAL" },
  { no: 2, name: "ANALYSIS_TRIGGER_AFTER_INGESTION" },
  { no: 3, name: "ANALYSIS_TRIGGER_SCHEDULE" },
]);

/**
 * @generated from message clearmind.v1.MatchOverride
 */
export class MatchOverride extends Message<MatchOverride> {
  /**
   * @generated from field: clearmind.v1.MatchVerdict verdict = 1;
   */
  verdict = MatchVerdict.UNSPECIFIED;

  /**
   * @generated from field: string app_user_id = 2;
   */
  appUserId = "";

  /**
   * @generated from field: string app_username = 3;
   */
  appUsername = "";

  /**
   * @generated from field: google.protobuf.Timestamp decided_at = 4;
   */
  decidedAt?: Timestamp;

  constructor(data?: PartialMessage<MatchOverride>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.MatchOverride";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "verdict", kind: "enum", T: proto3.getEnumType(MatchVerdict) },
    { no: 2, name: "app_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "app_username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "decided_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MatchOverride {
    return new MatchOverride().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MatchOverride {
    return new MatchOverride().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MatchOverride {
    return new MatchOverride().fromJsonString(jsonString, options);
  }

  static equals(a: MatchOverride | PlainMessage<MatchOverride> | undefined, b: MatchOverride | PlainMessage<MatchOverride> | undefined): boolean {
    return proto3.util.equals(MatchOverride, a, b);
  }
}

/**
 * @generated from message clearmind.v1.MatchHistoryEntry
 */
export class MatchHistoryEntry extends Message<MatchHistoryEntry> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: clearmind.v1.MatchEventKind kind = 2;
   */
  kind = MatchEventKind.UNSPECIFIED;

  /**
   * @generated from field: string app_user_id = 3;
   */
  appUserId = "";

  /**
   * @generated from field: string app_username = 4;
   */
  appUsername = "";

  /**
   * @generated from field: google.protobuf.Timestamp occurred_at = 5;
   */
  occurredAt?: Timestamp;

  constructor(data?: PartialMessage<MatchHistoryEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.MatchHistoryEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(MatchEventKind) },
    { no: 3, name: "app_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "app_username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "occurred_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MatchHistoryEntry {
    return new MatchHistoryEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MatchHistoryEntry {
    return new MatchHistoryEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MatchHistoryEntry {
    return new MatchHistoryEntry().fromJsonString(jsonString, options);
  }

  static equals(a: MatchHistoryEntry | PlainMessage<MatchHistoryEntry> | undefined, b: MatchHistoryEntry | PlainMessage<MatchHistoryEntry> | undefined): boolean {
    return proto3.util.equals(MatchHistoryEntry, a, b);
  }
}

/**
 * @generated from message clearmind.v1.EvidenceItem
 */
export class EvidenceItem extends Message<EvidenceItem> {
  /**
   * @generated from field: clearmind.v1.SignalKind signal = 1;
   */
  signal = SignalKind.UNSPECIFIED;

  /**
   * @generated from field: double value = 2;
   */
  value = 0;

  /**
   * @generated from field: int32 sample_size = 3;
   */
  sampleSize = 0;

  /**
   * @generated from field: string explanation = 4;
   */
  explanation = "";

  constructor(data?: PartialMessage<EvidenceItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.EvidenceItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signal", kind: "enum", T: proto3.getEnumType(SignalKind) },
    { no: 2, name: "value", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "sample_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "explanation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EvidenceItem {
    return new EvidenceItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EvidenceItem {
    return new EvidenceItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EvidenceItem {
    return new EvidenceItem().fromJsonString(jsonString, options);
  }

  static equals(a: EvidenceItem | PlainMessage<EvidenceItem> | undefined, b: EvidenceItem | PlainMessage<EvidenceItem> | undefined): boolean {
    return proto3.util.equals(EvidenceItem, a, b);
  }
}

/**
 * @generated from message clearmind.v1.MatchSample
 */
export class MatchSample extends Message<MatchSample> {
  /**
   * @generated from field: string left_channel_id = 1;
   */
  leftChannelId = "";

  /**
   * @generated from field: string left_post_foreign_id = 2;
   */
  leftPostForeignId = "";

  /**
   * @generated from field: google.protobuf.Timestamp left_published_at = 3;
   */
  leftPublishedAt?: Timestamp;

  /**
   * @generated from field: string left_excerpt = 4;
   */
  leftExcerpt = "";

  /**
   * @generated from field: string right_channel_id = 5;
   */
  rightChannelId = "";

  /**
   * @generated from field: string right_post_foreign_id = 6;
   */
  rightPostForeignId = "";

  /**
   * @generated from field: google.protobuf.Timestamp right_published_at = 7;
   */
  rightPublishedAt?: Timestamp;

  /**
   * @generated from field: string right_excerpt = 8;
   */
  rightExcerpt = "";

  /**
   * @generated from field: double similarity = 9;
   */
  similarity = 0;

  /**
   * @generated from field: bool attributed = 10;
   */
  attributed = false;

  constructor(data?: PartialMessage<MatchSample>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.MatchSample";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "left_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "left_post_foreign_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "left_published_at", kind: "message", T: Timestamp },
    { no: 4, name: "left_excerpt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "right_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "right_post_foreign_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "right_published_at", kind: "message", T: Timestamp },
    { no: 8, name: "right_excerpt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "similarity", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 10, name: "attributed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MatchSample {
    return new MatchSample().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MatchSample {
    return new MatchSample().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MatchSample {
    return new MatchSample().fromJsonString(jsonString, options);
  }

  static equals(a: MatchSample | PlainMessage<MatchSample> | undefined, b: MatchSample | PlainMessage<MatchSample> | undefined): boolean {
    return proto3.util.equals(MatchSample, a, b);
  }
}

/**
 * @generated from message clearmind.v1.AttributedEvidence
 */
export class AttributedEvidence extends Message<AttributedEvidence> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: int32 attributed_count = 2;
   */
  attributedCount = 0;

  /**
   * @generated from field: int32 post_count = 3;
   */
  postCount = 0;

  /**
   * @generated from field: double share = 4;
   */
  share = 0;

  constructor(data?: PartialMessage<AttributedEvidence>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AttributedEvidence";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "attributed_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "post_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "share", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AttributedEvidence {
    return new AttributedEvidence().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AttributedEvidence {
    return new AttributedEvidence().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AttributedEvidence {
    return new AttributedEvidence().fromJsonString(jsonString, options);
  }

  static equals(a: AttributedEvidence | PlainMessage<AttributedEvidence> | undefined, b: AttributedEvidence | PlainMessage<AttributedEvidence> | undefined): boolean {
    return proto3.util.equals(AttributedEvidence, a, b);
  }
}

/**
 * @generated from message clearmind.v1.EvidenceBundle
 */
export class EvidenceBundle extends Message<EvidenceBundle> {
  /**
   * @generated from field: double match_rate = 1;
   */
  matchRate = 0;

  /**
   * @generated from field: string earlier_channel_id = 2;
   */
  earlierChannelId = "";

  /**
   * @generated from field: double median_delay_seconds = 3;
   */
  medianDelaySeconds = 0;

  /**
   * @generated from field: double left_unique_share = 4;
   */
  leftUniqueShare = 0;

  /**
   * @generated from field: double right_unique_share = 5;
   */
  rightUniqueShare = 0;

  /**
   * @generated from field: double content_loss_risk = 6;
   */
  contentLossRisk = 0;

  /**
   * @generated from field: repeated clearmind.v1.EvidenceItem signals = 7;
   */
  signals: EvidenceItem[] = [];

  /**
   * @generated from field: repeated clearmind.v1.MatchSample samples = 8;
   */
  samples: MatchSample[] = [];

  /**
   * @generated from field: repeated clearmind.v1.AttributedEvidence attributed = 9;
   */
  attributed: AttributedEvidence[] = [];

  constructor(data?: PartialMessage<EvidenceBundle>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.EvidenceBundle";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "match_rate", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "earlier_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "median_delay_seconds", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "left_unique_share", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "right_unique_share", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "content_loss_risk", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "signals", kind: "message", T: EvidenceItem, repeated: true },
    { no: 8, name: "samples", kind: "message", T: MatchSample, repeated: true },
    { no: 9, name: "attributed", kind: "message", T: AttributedEvidence, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EvidenceBundle {
    return new EvidenceBundle().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EvidenceBundle {
    return new EvidenceBundle().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EvidenceBundle {
    return new EvidenceBundle().fromJsonString(jsonString, options);
  }

  static equals(a: EvidenceBundle | PlainMessage<EvidenceBundle> | undefined, b: EvidenceBundle | PlainMessage<EvidenceBundle> | undefined): boolean {
    return proto3.util.equals(EvidenceBundle, a, b);
  }
}

/**
 * @generated from message clearmind.v1.DuplicationCandidate
 */
export class DuplicationCandidate extends Message<DuplicationCandidate> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId = "";

  /**
   * @generated from field: string left_channel_id = 3;
   */
  leftChannelId = "";

  /**
   * @generated from field: string right_channel_id = 4;
   */
  rightChannelId = "";

  /**
   * @generated from field: clearmind.v1.RelationKind relation = 5;
   */
  relation = RelationKind.UNSPECIFIED;

  /**
   * @generated from field: double confidence = 6;
   */
  confidence = 0;

  /**
   * @generated from field: bool has_sufficient_data = 7;
   */
  hasSufficientData = false;

  /**
   * @generated from field: string algorithm_version = 8;
   */
  algorithmVersion = "";

  /**
   * @generated from field: clearmind.v1.EvidenceBundle evidence = 9;
   */
  evidence?: EvidenceBundle;

  /**
   * @generated from field: google.protobuf.Timestamp computed_at = 10;
   */
  computedAt?: Timestamp;

  /**
   * @generated from field: bool has_match_override = 11;
   */
  hasMatchOverride = false;

  /**
   * @generated from field: clearmind.v1.MatchOverride match_override = 12;
   */
  matchOverride?: MatchOverride;

  /**
   * @generated from field: repeated clearmind.v1.MatchHistoryEntry match_history = 13;
   */
  matchHistory: MatchHistoryEntry[] = [];

  constructor(data?: PartialMessage<DuplicationCandidate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.DuplicationCandidate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "left_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "right_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "relation", kind: "enum", T: proto3.getEnumType(RelationKind) },
    { no: 6, name: "confidence", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "has_sufficient_data", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "algorithm_version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "evidence", kind: "message", T: EvidenceBundle },
    { no: 10, name: "computed_at", kind: "message", T: Timestamp },
    { no: 11, name: "has_match_override", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "match_override", kind: "message", T: MatchOverride },
    { no: 13, name: "match_history", kind: "message", T: MatchHistoryEntry, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DuplicationCandidate {
    return new DuplicationCandidate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DuplicationCandidate {
    return new DuplicationCandidate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DuplicationCandidate {
    return new DuplicationCandidate().fromJsonString(jsonString, options);
  }

  static equals(a: DuplicationCandidate | PlainMessage<DuplicationCandidate> | undefined, b: DuplicationCandidate | PlainMessage<DuplicationCandidate> | undefined): boolean {
    return proto3.util.equals(DuplicationCandidate, a, b);
  }
}

/**
 * @generated from message clearmind.v1.DuplicationCluster
 */
export class DuplicationCluster extends Message<DuplicationCluster> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId = "";

  /**
   * @generated from field: repeated string channel_ids = 3;
   */
  channelIds: string[] = [];

  /**
   * @generated from field: repeated string candidate_ids = 4;
   */
  candidateIds: string[] = [];

  constructor(data?: PartialMessage<DuplicationCluster>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.DuplicationCluster";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "channel_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "candidate_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DuplicationCluster {
    return new DuplicationCluster().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DuplicationCluster {
    return new DuplicationCluster().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DuplicationCluster {
    return new DuplicationCluster().fromJsonString(jsonString, options);
  }

  static equals(a: DuplicationCluster | PlainMessage<DuplicationCluster> | undefined, b: DuplicationCluster | PlainMessage<DuplicationCluster> | undefined): boolean {
    return proto3.util.equals(DuplicationCluster, a, b);
  }
}

/**
 * @generated from message clearmind.v1.AnalysisStageProgress
 */
export class AnalysisStageProgress extends Message<AnalysisStageProgress> {
  /**
   * @generated from field: clearmind.v1.AnalysisStage stage = 1;
   */
  stage = AnalysisStage.UNSPECIFIED;

  /**
   * @generated from field: int32 done_units = 2;
   */
  doneUnits = 0;

  /**
   * @generated from field: optional int32 total_units = 3;
   */
  totalUnits?: number;

  constructor(data?: PartialMessage<AnalysisStageProgress>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AnalysisStageProgress";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stage", kind: "enum", T: proto3.getEnumType(AnalysisStage) },
    { no: 2, name: "done_units", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "total_units", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalysisStageProgress {
    return new AnalysisStageProgress().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalysisStageProgress {
    return new AnalysisStageProgress().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalysisStageProgress {
    return new AnalysisStageProgress().fromJsonString(jsonString, options);
  }

  static equals(a: AnalysisStageProgress | PlainMessage<AnalysisStageProgress> | undefined, b: AnalysisStageProgress | PlainMessage<AnalysisStageProgress> | undefined): boolean {
    return proto3.util.equals(AnalysisStageProgress, a, b);
  }
}

/**
 * @generated from message clearmind.v1.AnalysisRun
 */
export class AnalysisRun extends Message<AnalysisRun> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId = "";

  /**
   * @generated from field: clearmind.v1.RunStatus status = 3;
   */
  status = RunStatus.UNSPECIFIED;

  /**
   * @generated from field: string algorithm_version = 4;
   */
  algorithmVersion = "";

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 5;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp finished_at = 6;
   */
  finishedAt?: Timestamp;

  /**
   * @generated from field: int32 posts_analyzed = 7;
   */
  postsAnalyzed = 0;

  /**
   * @generated from field: int32 pairs_compared = 8;
   */
  pairsCompared = 0;

  /**
   * @generated from field: int32 candidates_found = 9;
   */
  candidatesFound = 0;

  /**
   * @generated from field: repeated clearmind.v1.ChannelError channel_errors = 10;
   */
  channelErrors: ChannelError[] = [];

  /**
   * @generated from field: repeated clearmind.v1.AnalysisStageProgress stages = 11;
   */
  stages: AnalysisStageProgress[] = [];

  /**
   * @generated from field: clearmind.v1.AnalysisStage current_stage = 12;
   */
  currentStage = AnalysisStage.UNSPECIFIED;

  /**
   * @generated from field: clearmind.v1.AnalysisTrigger trigger = 13;
   */
  trigger = AnalysisTrigger.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp enqueued_at = 14;
   */
  enqueuedAt?: Timestamp;

  /**
   * @generated from field: optional int32 queue_position = 15;
   */
  queuePosition?: number;

  /**
   * @generated from field: string awaited_ingestion_run_id = 16;
   */
  awaitedIngestionRunId = "";

  /**
   * @generated from field: optional clearmind.v1.RunFailure failure = 17;
   */
  failure?: RunFailure;

  constructor(data?: PartialMessage<AnalysisRun>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.AnalysisRun";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(RunStatus) },
    { no: 4, name: "algorithm_version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "started_at", kind: "message", T: Timestamp },
    { no: 6, name: "finished_at", kind: "message", T: Timestamp },
    { no: 7, name: "posts_analyzed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "pairs_compared", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "candidates_found", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "channel_errors", kind: "message", T: ChannelError, repeated: true },
    { no: 11, name: "stages", kind: "message", T: AnalysisStageProgress, repeated: true },
    { no: 12, name: "current_stage", kind: "enum", T: proto3.getEnumType(AnalysisStage) },
    { no: 13, name: "trigger", kind: "enum", T: proto3.getEnumType(AnalysisTrigger) },
    { no: 14, name: "enqueued_at", kind: "message", T: Timestamp },
    { no: 15, name: "queue_position", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 16, name: "awaited_ingestion_run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "failure", kind: "message", T: RunFailure, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalysisRun {
    return new AnalysisRun().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalysisRun {
    return new AnalysisRun().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalysisRun {
    return new AnalysisRun().fromJsonString(jsonString, options);
  }

  static equals(a: AnalysisRun | PlainMessage<AnalysisRun> | undefined, b: AnalysisRun | PlainMessage<AnalysisRun> | undefined): boolean {
    return proto3.util.equals(AnalysisRun, a, b);
  }
}

/**
 * @generated from message clearmind.v1.StartAnalysisRequest
 */
export class StartAnalysisRequest extends Message<StartAnalysisRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: string after_ingestion_run_id = 2;
   */
  afterIngestionRunId = "";

  constructor(data?: PartialMessage<StartAnalysisRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.StartAnalysisRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "after_ingestion_run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartAnalysisRequest {
    return new StartAnalysisRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartAnalysisRequest {
    return new StartAnalysisRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartAnalysisRequest {
    return new StartAnalysisRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartAnalysisRequest | PlainMessage<StartAnalysisRequest> | undefined, b: StartAnalysisRequest | PlainMessage<StartAnalysisRequest> | undefined): boolean {
    return proto3.util.equals(StartAnalysisRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.StartAnalysisResponse
 */
export class StartAnalysisResponse extends Message<StartAnalysisResponse> {
  /**
   * @generated from field: clearmind.v1.AnalysisRun run = 1;
   */
  run?: AnalysisRun;

  constructor(data?: PartialMessage<StartAnalysisResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.StartAnalysisResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run", kind: "message", T: AnalysisRun },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartAnalysisResponse {
    return new StartAnalysisResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartAnalysisResponse {
    return new StartAnalysisResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartAnalysisResponse {
    return new StartAnalysisResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartAnalysisResponse | PlainMessage<StartAnalysisResponse> | undefined, b: StartAnalysisResponse | PlainMessage<StartAnalysisResponse> | undefined): boolean {
    return proto3.util.equals(StartAnalysisResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.CancelAnalysisRunRequest
 */
export class CancelAnalysisRunRequest extends Message<CancelAnalysisRunRequest> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId = "";

  constructor(data?: PartialMessage<CancelAnalysisRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.CancelAnalysisRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelAnalysisRunRequest {
    return new CancelAnalysisRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelAnalysisRunRequest {
    return new CancelAnalysisRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelAnalysisRunRequest {
    return new CancelAnalysisRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelAnalysisRunRequest | PlainMessage<CancelAnalysisRunRequest> | undefined, b: CancelAnalysisRunRequest | PlainMessage<CancelAnalysisRunRequest> | undefined): boolean {
    return proto3.util.equals(CancelAnalysisRunRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.CancelAnalysisRunResponse
 */
export class CancelAnalysisRunResponse extends Message<CancelAnalysisRunResponse> {
  /**
   * @generated from field: clearmind.v1.AnalysisRun run = 1;
   */
  run?: AnalysisRun;

  constructor(data?: PartialMessage<CancelAnalysisRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.CancelAnalysisRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run", kind: "message", T: AnalysisRun },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelAnalysisRunResponse {
    return new CancelAnalysisRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelAnalysisRunResponse {
    return new CancelAnalysisRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelAnalysisRunResponse {
    return new CancelAnalysisRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelAnalysisRunResponse | PlainMessage<CancelAnalysisRunResponse> | undefined, b: CancelAnalysisRunResponse | PlainMessage<CancelAnalysisRunResponse> | undefined): boolean {
    return proto3.util.equals(CancelAnalysisRunResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetAnalysisRunRequest
 */
export class GetAnalysisRunRequest extends Message<GetAnalysisRunRequest> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId = "";

  constructor(data?: PartialMessage<GetAnalysisRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetAnalysisRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAnalysisRunRequest {
    return new GetAnalysisRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAnalysisRunRequest {
    return new GetAnalysisRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAnalysisRunRequest {
    return new GetAnalysisRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAnalysisRunRequest | PlainMessage<GetAnalysisRunRequest> | undefined, b: GetAnalysisRunRequest | PlainMessage<GetAnalysisRunRequest> | undefined): boolean {
    return proto3.util.equals(GetAnalysisRunRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetAnalysisRunResponse
 */
export class GetAnalysisRunResponse extends Message<GetAnalysisRunResponse> {
  /**
   * @generated from field: clearmind.v1.AnalysisRun run = 1;
   */
  run?: AnalysisRun;

  constructor(data?: PartialMessage<GetAnalysisRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetAnalysisRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run", kind: "message", T: AnalysisRun },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAnalysisRunResponse {
    return new GetAnalysisRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAnalysisRunResponse {
    return new GetAnalysisRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAnalysisRunResponse {
    return new GetAnalysisRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAnalysisRunResponse | PlainMessage<GetAnalysisRunResponse> | undefined, b: GetAnalysisRunResponse | PlainMessage<GetAnalysisRunResponse> | undefined): boolean {
    return proto3.util.equals(GetAnalysisRunResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListAnalysisRunsRequest
 */
export class ListAnalysisRunsRequest extends Message<ListAnalysisRunsRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: clearmind.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListAnalysisRunsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListAnalysisRunsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAnalysisRunsRequest {
    return new ListAnalysisRunsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAnalysisRunsRequest {
    return new ListAnalysisRunsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAnalysisRunsRequest {
    return new ListAnalysisRunsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListAnalysisRunsRequest | PlainMessage<ListAnalysisRunsRequest> | undefined, b: ListAnalysisRunsRequest | PlainMessage<ListAnalysisRunsRequest> | undefined): boolean {
    return proto3.util.equals(ListAnalysisRunsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListAnalysisRunsResponse
 */
export class ListAnalysisRunsResponse extends Message<ListAnalysisRunsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.AnalysisRun runs = 1;
   */
  runs: AnalysisRun[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListAnalysisRunsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListAnalysisRunsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runs", kind: "message", T: AnalysisRun, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAnalysisRunsResponse {
    return new ListAnalysisRunsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAnalysisRunsResponse {
    return new ListAnalysisRunsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAnalysisRunsResponse {
    return new ListAnalysisRunsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListAnalysisRunsResponse | PlainMessage<ListAnalysisRunsResponse> | undefined, b: ListAnalysisRunsResponse | PlainMessage<ListAnalysisRunsResponse> | undefined): boolean {
    return proto3.util.equals(ListAnalysisRunsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListCandidatesRequest
 */
export class ListCandidatesRequest extends Message<ListCandidatesRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: repeated clearmind.v1.RelationKind relations = 2;
   */
  relations: RelationKind[] = [];

  /**
   * @generated from field: clearmind.v1.PageRequest page = 3;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListCandidatesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListCandidatesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "relations", kind: "enum", T: proto3.getEnumType(RelationKind), repeated: true },
    { no: 3, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCandidatesRequest {
    return new ListCandidatesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCandidatesRequest {
    return new ListCandidatesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCandidatesRequest {
    return new ListCandidatesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListCandidatesRequest | PlainMessage<ListCandidatesRequest> | undefined, b: ListCandidatesRequest | PlainMessage<ListCandidatesRequest> | undefined): boolean {
    return proto3.util.equals(ListCandidatesRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListCandidatesResponse
 */
export class ListCandidatesResponse extends Message<ListCandidatesResponse> {
  /**
   * @generated from field: repeated clearmind.v1.DuplicationCandidate candidates = 1;
   */
  candidates: DuplicationCandidate[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListCandidatesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListCandidatesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidates", kind: "message", T: DuplicationCandidate, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCandidatesResponse {
    return new ListCandidatesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCandidatesResponse {
    return new ListCandidatesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCandidatesResponse {
    return new ListCandidatesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListCandidatesResponse | PlainMessage<ListCandidatesResponse> | undefined, b: ListCandidatesResponse | PlainMessage<ListCandidatesResponse> | undefined): boolean {
    return proto3.util.equals(ListCandidatesResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetCandidateRequest
 */
export class GetCandidateRequest extends Message<GetCandidateRequest> {
  /**
   * @generated from field: string candidate_id = 1;
   */
  candidateId = "";

  constructor(data?: PartialMessage<GetCandidateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetCandidateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCandidateRequest {
    return new GetCandidateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCandidateRequest {
    return new GetCandidateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCandidateRequest {
    return new GetCandidateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCandidateRequest | PlainMessage<GetCandidateRequest> | undefined, b: GetCandidateRequest | PlainMessage<GetCandidateRequest> | undefined): boolean {
    return proto3.util.equals(GetCandidateRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetCandidateResponse
 */
export class GetCandidateResponse extends Message<GetCandidateResponse> {
  /**
   * @generated from field: clearmind.v1.DuplicationCandidate candidate = 1;
   */
  candidate?: DuplicationCandidate;

  constructor(data?: PartialMessage<GetCandidateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetCandidateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate", kind: "message", T: DuplicationCandidate },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCandidateResponse {
    return new GetCandidateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCandidateResponse {
    return new GetCandidateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCandidateResponse {
    return new GetCandidateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetCandidateResponse | PlainMessage<GetCandidateResponse> | undefined, b: GetCandidateResponse | PlainMessage<GetCandidateResponse> | undefined): boolean {
    return proto3.util.equals(GetCandidateResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListClustersRequest
 */
export class ListClustersRequest extends Message<ListClustersRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: clearmind.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListClustersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListClustersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListClustersRequest {
    return new ListClustersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListClustersRequest {
    return new ListClustersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListClustersRequest {
    return new ListClustersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListClustersRequest | PlainMessage<ListClustersRequest> | undefined, b: ListClustersRequest | PlainMessage<ListClustersRequest> | undefined): boolean {
    return proto3.util.equals(ListClustersRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListClustersResponse
 */
export class ListClustersResponse extends Message<ListClustersResponse> {
  /**
   * @generated from field: repeated clearmind.v1.DuplicationCluster clusters = 1;
   */
  clusters: DuplicationCluster[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListClustersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListClustersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "clusters", kind: "message", T: DuplicationCluster, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListClustersResponse {
    return new ListClustersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListClustersResponse {
    return new ListClustersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListClustersResponse {
    return new ListClustersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListClustersResponse | PlainMessage<ListClustersResponse> | undefined, b: ListClustersResponse | PlainMessage<ListClustersResponse> | undefined): boolean {
    return proto3.util.equals(ListClustersResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.UniquePost
 */
export class UniquePost extends Message<UniquePost> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: string post_foreign_id = 2;
   */
  postForeignId = "";

  /**
   * @generated from field: google.protobuf.Timestamp published_at = 3;
   */
  publishedAt?: Timestamp;

  /**
   * @generated from field: string excerpt = 4;
   */
  excerpt = "";

  constructor(data?: PartialMessage<UniquePost>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.UniquePost";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "post_foreign_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "published_at", kind: "message", T: Timestamp },
    { no: 4, name: "excerpt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UniquePost {
    return new UniquePost().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UniquePost {
    return new UniquePost().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UniquePost {
    return new UniquePost().fromJsonString(jsonString, options);
  }

  static equals(a: UniquePost | PlainMessage<UniquePost> | undefined, b: UniquePost | PlainMessage<UniquePost> | undefined): boolean {
    return proto3.util.equals(UniquePost, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListUniquePostsRequest
 */
export class ListUniquePostsRequest extends Message<ListUniquePostsRequest> {
  /**
   * @generated from field: string candidate_id = 1;
   */
  candidateId = "";

  /**
   * @generated from field: string channel_id = 2;
   */
  channelId = "";

  /**
   * @generated from field: clearmind.v1.PageRequest page = 3;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListUniquePostsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListUniquePostsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUniquePostsRequest {
    return new ListUniquePostsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUniquePostsRequest {
    return new ListUniquePostsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUniquePostsRequest {
    return new ListUniquePostsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListUniquePostsRequest | PlainMessage<ListUniquePostsRequest> | undefined, b: ListUniquePostsRequest | PlainMessage<ListUniquePostsRequest> | undefined): boolean {
    return proto3.util.equals(ListUniquePostsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListUniquePostsResponse
 */
export class ListUniquePostsResponse extends Message<ListUniquePostsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.UniquePost posts = 1;
   */
  posts: UniquePost[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  /**
   * @generated from field: int32 total_count = 3;
   */
  totalCount = 0;

  constructor(data?: PartialMessage<ListUniquePostsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListUniquePostsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "posts", kind: "message", T: UniquePost, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
    { no: 3, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUniquePostsResponse {
    return new ListUniquePostsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUniquePostsResponse {
    return new ListUniquePostsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUniquePostsResponse {
    return new ListUniquePostsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListUniquePostsResponse | PlainMessage<ListUniquePostsResponse> | undefined, b: ListUniquePostsResponse | PlainMessage<ListUniquePostsResponse> | undefined): boolean {
    return proto3.util.equals(ListUniquePostsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.SetCandidateMatchRequest
 */
export class SetCandidateMatchRequest extends Message<SetCandidateMatchRequest> {
  /**
   * @generated from field: string candidate_id = 1;
   */
  candidateId = "";

  /**
   * @generated from field: clearmind.v1.MatchVerdict verdict = 2;
   */
  verdict = MatchVerdict.UNSPECIFIED;

  constructor(data?: PartialMessage<SetCandidateMatchRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.SetCandidateMatchRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "verdict", kind: "enum", T: proto3.getEnumType(MatchVerdict) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetCandidateMatchRequest {
    return new SetCandidateMatchRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetCandidateMatchRequest {
    return new SetCandidateMatchRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetCandidateMatchRequest {
    return new SetCandidateMatchRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetCandidateMatchRequest | PlainMessage<SetCandidateMatchRequest> | undefined, b: SetCandidateMatchRequest | PlainMessage<SetCandidateMatchRequest> | undefined): boolean {
    return proto3.util.equals(SetCandidateMatchRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.SetCandidateMatchResponse
 */
export class SetCandidateMatchResponse extends Message<SetCandidateMatchResponse> {
  /**
   * @generated from field: clearmind.v1.DuplicationCandidate candidate = 1;
   */
  candidate?: DuplicationCandidate;

  constructor(data?: PartialMessage<SetCandidateMatchResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.SetCandidateMatchResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate", kind: "message", T: DuplicationCandidate },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetCandidateMatchResponse {
    return new SetCandidateMatchResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetCandidateMatchResponse {
    return new SetCandidateMatchResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetCandidateMatchResponse {
    return new SetCandidateMatchResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetCandidateMatchResponse | PlainMessage<SetCandidateMatchResponse> | undefined, b: SetCandidateMatchResponse | PlainMessage<SetCandidateMatchResponse> | undefined): boolean {
    return proto3.util.equals(SetCandidateMatchResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ResetCandidateMatchRequest
 */
export class ResetCandidateMatchRequest extends Message<ResetCandidateMatchRequest> {
  /**
   * @generated from field: string candidate_id = 1;
   */
  candidateId = "";

  constructor(data?: PartialMessage<ResetCandidateMatchRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ResetCandidateMatchRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetCandidateMatchRequest {
    return new ResetCandidateMatchRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetCandidateMatchRequest {
    return new ResetCandidateMatchRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetCandidateMatchRequest {
    return new ResetCandidateMatchRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResetCandidateMatchRequest | PlainMessage<ResetCandidateMatchRequest> | undefined, b: ResetCandidateMatchRequest | PlainMessage<ResetCandidateMatchRequest> | undefined): boolean {
    return proto3.util.equals(ResetCandidateMatchRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ResetCandidateMatchResponse
 */
export class ResetCandidateMatchResponse extends Message<ResetCandidateMatchResponse> {
  /**
   * @generated from field: clearmind.v1.DuplicationCandidate candidate = 1;
   */
  candidate?: DuplicationCandidate;

  constructor(data?: PartialMessage<ResetCandidateMatchResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ResetCandidateMatchResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "candidate", kind: "message", T: DuplicationCandidate },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetCandidateMatchResponse {
    return new ResetCandidateMatchResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetCandidateMatchResponse {
    return new ResetCandidateMatchResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetCandidateMatchResponse {
    return new ResetCandidateMatchResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ResetCandidateMatchResponse | PlainMessage<ResetCandidateMatchResponse> | undefined, b: ResetCandidateMatchResponse | PlainMessage<ResetCandidateMatchResponse> | undefined): boolean {
    return proto3.util.equals(ResetCandidateMatchResponse, a, b);
  }
}

