// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/duplication.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelAnalysisRunRequest, CancelAnalysisRunResponse, GetAnalysisRunRequest, GetAnalysisRunResponse, GetCandidateRequest, GetCandidateResponse, ListAnalysisRunsRequest, ListAnalysisRunsResponse, ListCandidatesRequest, ListCandidatesResponse, ListClustersRequest, ListClustersResponse, ListUniquePostsRequest, ListUniquePostsResponse, ResetCandidateMatchRequest, ResetCandidateMatchResponse, SetCandidateMatchRequest, SetCandidateMatchResponse, StartAnalysisRequest, StartAnalysisResponse } from "./duplication_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.DuplicationService
 */
export const DuplicationService = {
  typeName: "clearmind.v1.DuplicationService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.DuplicationService.StartAnalysis
     */
    startAnalysis: {
      name: "StartAnalysis",
      I: StartAnalysisRequest,
      O: StartAnalysisResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.CancelAnalysisRun
     */
    cancelAnalysisRun: {
      name: "CancelAnalysisRun",
      I: CancelAnalysisRunRequest,
      O: CancelAnalysisRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.GetAnalysisRun
     */
    getAnalysisRun: {
      name: "GetAnalysisRun",
      I: GetAnalysisRunRequest,
      O: GetAnalysisRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.ListAnalysisRuns
     */
    listAnalysisRuns: {
      name: "ListAnalysisRuns",
      I: ListAnalysisRunsRequest,
      O: ListAnalysisRunsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.ListCandidates
     */
    listCandidates: {
      name: "ListCandidates",
      I: ListCandidatesRequest,
      O: ListCandidatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.GetCandidate
     */
    getCandidate: {
      name: "GetCandidate",
      I: GetCandidateRequest,
      O: GetCandidateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.ListClusters
     */
    listClusters: {
      name: "ListClusters",
      I: ListClustersRequest,
      O: ListClustersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.ListUniquePosts
     */
    listUniquePosts: {
      name: "ListUniquePosts",
      I: ListUniquePostsRequest,
      O: ListUniquePostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.SetCandidateMatch
     */
    setCandidateMatch: {
      name: "SetCandidateMatch",
      I: SetCandidateMatchRequest,
      O: SetCandidateMatchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.DuplicationService.ResetCandidateMatch
     */
    resetCandidateMatch: {
      name: "ResetCandidateMatch",
      I: ResetCandidateMatchRequest,
      O: ResetCandidateMatchResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

