// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/ingestion.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetIngestionRunRequest, GetIngestionRunResponse, ListIngestionRunsRequest, ListIngestionRunsResponse, StartIngestionRequest, StartIngestionResponse } from "./ingestion_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.IngestionService
 */
export const IngestionService = {
  typeName: "clearmind.v1.IngestionService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.IngestionService.StartIngestion
     */
    startIngestion: {
      name: "StartIngestion",
      I: StartIngestionRequest,
      O: StartIngestionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.IngestionService.GetIngestionRun
     */
    getIngestionRun: {
      name: "GetIngestionRun",
      I: GetIngestionRunRequest,
      O: GetIngestionRunResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.IngestionService.ListIngestionRuns
     */
    listIngestionRuns: {
      name: "ListIngestionRuns",
      I: ListIngestionRunsRequest,
      O: ListIngestionRunsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

