// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/ingestion.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { ChannelError, PageRequest, PageResponse, RunFailure, RunStatus } from "./common_pb.js";

/**
 * @generated from enum clearmind.v1.ChannelIngestionState
 */
export enum ChannelIngestionState {
  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_QUEUED = 1;
   */
  QUEUED = 1,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_COLLECTING = 2;
   */
  COLLECTING = 2,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_RATE_LIMITED = 3;
   */
  RATE_LIMITED = 3,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_DONE = 4;
   */
  DONE = 4,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_REUSED = 5;
   */
  REUSED = 5,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_FAILED = 6;
   */
  FAILED = 6,

  /**
   * @generated from enum value: CHANNEL_INGESTION_STATE_SKIPPED = 7;
   */
  SKIPPED = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(ChannelIngestionState)
proto3.util.setEnumType(ChannelIngestionState, "clearmind.v1.ChannelIngestionState", [
  { no: 0, name: "CHANNEL_INGESTION_STATE_UNSPECIFIED" },
  { no: 1, name: "CHANNEL_INGESTION_STATE_QUEUED" },
  { no: 2, name: "CHANNEL_INGESTION_STATE_COLLECTING" },
  { no: 3, name: "CHANNEL_INGESTION_STATE_RATE_LIMITED" },
  { no: 4, name: "CHANNEL_INGESTION_STATE_DONE" },
  { no: 5, name: "CHANNEL_INGESTION_STATE_REUSED" },
  { no: 6, name: "CHANNEL_INGESTION_STATE_FAILED" },
  { no: 7, name: "CHANNEL_INGESTION_STATE_SKIPPED" },
]);

/**
 * @generated from message clearmind.v1.ChannelIngestionProgress
 */
export class ChannelIngestionProgress extends Message<ChannelIngestionProgress> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: clearmind.v1.ChannelIngestionState state = 4;
   */
  state = ChannelIngestionState.UNSPECIFIED;

  /**
   * @generated from field: int32 posts_ingested = 5;
   */
  postsIngested = 0;

  /**
   * @generated from field: bool previously_collected = 6;
   */
  previouslyCollected = false;

  /**
   * @generated from field: google.protobuf.Timestamp collected_at = 7;
   */
  collectedAt?: Timestamp;

  /**
   * @generated from field: optional int32 retry_after_seconds = 8;
   */
  retryAfterSeconds?: number;

  constructor(data?: PartialMessage<ChannelIngestionProgress>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ChannelIngestionProgress";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "state", kind: "enum", T: proto3.getEnumType(ChannelIngestionState) },
    { no: 5, name: "posts_ingested", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "previously_collected", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "collected_at", kind: "message", T: Timestamp },
    { no: 8, name: "retry_after_seconds", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChannelIngestionProgress {
    return new ChannelIngestionProgress().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChannelIngestionProgress {
    return new ChannelIngestionProgress().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChannelIngestionProgress {
    return new ChannelIngestionProgress().fromJsonString(jsonString, options);
  }

  static equals(a: ChannelIngestionProgress | PlainMessage<ChannelIngestionProgress> | undefined, b: ChannelIngestionProgress | PlainMessage<ChannelIngestionProgress> | undefined): boolean {
    return proto3.util.equals(ChannelIngestionProgress, a, b);
  }
}

/**
 * @generated from message clearmind.v1.IngestionRun
 */
export class IngestionRun extends Message<IngestionRun> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId = "";

  /**
   * @generated from field: clearmind.v1.RunStatus status = 3;
   */
  status = RunStatus.UNSPECIFIED;

  /**
   * @generated from field: int32 window_days = 4;
   */
  windowDays = 0;

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 5;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp finished_at = 6;
   */
  finishedAt?: Timestamp;

  /**
   * @generated from field: int32 channels_total = 7;
   */
  channelsTotal = 0;

  /**
   * @generated from field: int32 channels_processed = 8;
   */
  channelsProcessed = 0;

  /**
   * @generated from field: int32 posts_ingested = 9;
   */
  postsIngested = 0;

  /**
   * @generated from field: repeated clearmind.v1.ChannelError channel_errors = 10;
   */
  channelErrors: ChannelError[] = [];

  /**
   * @generated from field: repeated clearmind.v1.ChannelIngestionProgress channels = 11;
   */
  channels: ChannelIngestionProgress[] = [];

  /**
   * @generated from field: int32 rate_limit_waits = 12;
   */
  rateLimitWaits = 0;

  /**
   * @generated from field: optional clearmind.v1.RunFailure failure = 13;
   */
  failure?: RunFailure;

  constructor(data?: PartialMessage<IngestionRun>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.IngestionRun";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(RunStatus) },
    { no: 4, name: "window_days", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "started_at", kind: "message", T: Timestamp },
    { no: 6, name: "finished_at", kind: "message", T: Timestamp },
    { no: 7, name: "channels_total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "channels_processed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "posts_ingested", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "channel_errors", kind: "message", T: ChannelError, repeated: true },
    { no: 11, name: "channels", kind: "message", T: ChannelIngestionProgress, repeated: true },
    { no: 12, name: "rate_limit_waits", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "failure", kind: "message", T: RunFailure, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IngestionRun {
    return new IngestionRun().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IngestionRun {
    return new IngestionRun().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IngestionRun {
    return new IngestionRun().fromJsonString(jsonString, options);
  }

  static equals(a: IngestionRun | PlainMessage<IngestionRun> | undefined, b: IngestionRun | PlainMessage<IngestionRun> | undefined): boolean {
    return proto3.util.equals(IngestionRun, a, b);
  }
}

/**
 * @generated from message clearmind.v1.StartIngestionRequest
 */
export class StartIngestionRequest extends Message<StartIngestionRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: int32 window_days = 2;
   */
  windowDays = 0;

  constructor(data?: PartialMessage<StartIngestionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.StartIngestionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "window_days", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartIngestionRequest {
    return new StartIngestionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartIngestionRequest {
    return new StartIngestionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartIngestionRequest {
    return new StartIngestionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartIngestionRequest | PlainMessage<StartIngestionRequest> | undefined, b: StartIngestionRequest | PlainMessage<StartIngestionRequest> | undefined): boolean {
    return proto3.util.equals(StartIngestionRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.StartIngestionResponse
 */
export class StartIngestionResponse extends Message<StartIngestionResponse> {
  /**
   * @generated from field: clearmind.v1.IngestionRun run = 1;
   */
  run?: IngestionRun;

  constructor(data?: PartialMessage<StartIngestionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.StartIngestionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run", kind: "message", T: IngestionRun },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartIngestionResponse {
    return new StartIngestionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartIngestionResponse {
    return new StartIngestionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartIngestionResponse {
    return new StartIngestionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartIngestionResponse | PlainMessage<StartIngestionResponse> | undefined, b: StartIngestionResponse | PlainMessage<StartIngestionResponse> | undefined): boolean {
    return proto3.util.equals(StartIngestionResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetIngestionRunRequest
 */
export class GetIngestionRunRequest extends Message<GetIngestionRunRequest> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId = "";

  constructor(data?: PartialMessage<GetIngestionRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetIngestionRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetIngestionRunRequest {
    return new GetIngestionRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetIngestionRunRequest {
    return new GetIngestionRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetIngestionRunRequest {
    return new GetIngestionRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetIngestionRunRequest | PlainMessage<GetIngestionRunRequest> | undefined, b: GetIngestionRunRequest | PlainMessage<GetIngestionRunRequest> | undefined): boolean {
    return proto3.util.equals(GetIngestionRunRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetIngestionRunResponse
 */
export class GetIngestionRunResponse extends Message<GetIngestionRunResponse> {
  /**
   * @generated from field: clearmind.v1.IngestionRun run = 1;
   */
  run?: IngestionRun;

  constructor(data?: PartialMessage<GetIngestionRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetIngestionRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "run", kind: "message", T: IngestionRun },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetIngestionRunResponse {
    return new GetIngestionRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetIngestionRunResponse {
    return new GetIngestionRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetIngestionRunResponse {
    return new GetIngestionRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetIngestionRunResponse | PlainMessage<GetIngestionRunResponse> | undefined, b: GetIngestionRunResponse | PlainMessage<GetIngestionRunResponse> | undefined): boolean {
    return proto3.util.equals(GetIngestionRunResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListIngestionRunsRequest
 */
export class ListIngestionRunsRequest extends Message<ListIngestionRunsRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: clearmind.v1.PageRequest page = 2;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListIngestionRunsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListIngestionRunsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListIngestionRunsRequest {
    return new ListIngestionRunsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListIngestionRunsRequest {
    return new ListIngestionRunsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListIngestionRunsRequest {
    return new ListIngestionRunsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListIngestionRunsRequest | PlainMessage<ListIngestionRunsRequest> | undefined, b: ListIngestionRunsRequest | PlainMessage<ListIngestionRunsRequest> | undefined): boolean {
    return proto3.util.equals(ListIngestionRunsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListIngestionRunsResponse
 */
export class ListIngestionRunsResponse extends Message<ListIngestionRunsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.IngestionRun runs = 1;
   */
  runs: IngestionRun[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListIngestionRunsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListIngestionRunsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runs", kind: "message", T: IngestionRun, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListIngestionRunsResponse {
    return new ListIngestionRunsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListIngestionRunsResponse {
    return new ListIngestionRunsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListIngestionRunsResponse {
    return new ListIngestionRunsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListIngestionRunsResponse | PlainMessage<ListIngestionRunsResponse> | undefined, b: ListIngestionRunsResponse | PlainMessage<ListIngestionRunsResponse> | undefined): boolean {
    return proto3.util.equals(ListIngestionRunsResponse, a, b);
  }
}

