// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/recommendation.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListDecisionsRequest, ListDecisionsResponse, ListRecommendationsRequest, ListRecommendationsResponse, SubmitDecisionRequest, SubmitDecisionResponse } from "./recommendation_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.RecommendationService
 */
export const RecommendationService = {
  typeName: "clearmind.v1.RecommendationService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.RecommendationService.ListRecommendations
     */
    listRecommendations: {
      name: "ListRecommendations",
      I: ListRecommendationsRequest,
      O: ListRecommendationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.RecommendationService.SubmitDecision
     */
    submitDecision: {
      name: "SubmitDecision",
      I: SubmitDecisionRequest,
      O: SubmitDecisionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.RecommendationService.ListDecisions
     */
    listDecisions: {
      name: "ListDecisions",
      I: ListDecisionsRequest,
      O: ListDecisionsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

