// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/recommendation.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { EvidenceBundle } from "./duplication_pb.js";
import { PageRequest, PageResponse } from "./common_pb.js";

/**
 * @generated from enum clearmind.v1.DecisionKind
 */
export enum DecisionKind {
  /**
   * @generated from enum value: DECISION_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DECISION_KIND_CONFIRMED = 1;
   */
  CONFIRMED = 1,

  /**
   * @generated from enum value: DECISION_KIND_REJECTED = 2;
   */
  REJECTED = 2,

  /**
   * @generated from enum value: DECISION_KIND_DEFERRED = 3;
   */
  DEFERRED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(DecisionKind)
proto3.util.setEnumType(DecisionKind, "clearmind.v1.DecisionKind", [
  { no: 0, name: "DECISION_KIND_UNSPECIFIED" },
  { no: 1, name: "DECISION_KIND_CONFIRMED" },
  { no: 2, name: "DECISION_KIND_REJECTED" },
  { no: 3, name: "DECISION_KIND_DEFERRED" },
]);

/**
 * @generated from message clearmind.v1.Recommendation
 */
export class Recommendation extends Message<Recommendation> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId = "";

  /**
   * @generated from field: string candidate_id = 3;
   */
  candidateId = "";

  /**
   * @generated from field: string subject_channel_id = 4;
   */
  subjectChannelId = "";

  /**
   * @generated from field: string reference_channel_id = 5;
   */
  referenceChannelId = "";

  /**
   * @generated from field: int64 version = 6;
   */
  version = protoInt64.zero;

  /**
   * @generated from field: string rationale = 7;
   */
  rationale = "";

  /**
   * @generated from field: clearmind.v1.EvidenceBundle evidence = 8;
   */
  evidence?: EvidenceBundle;

  /**
   * @generated from field: clearmind.v1.DecisionKind current_decision = 9;
   */
  currentDecision = DecisionKind.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Recommendation>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.Recommendation";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "candidate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "subject_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "reference_channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "rationale", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "evidence", kind: "message", T: EvidenceBundle },
    { no: 9, name: "current_decision", kind: "enum", T: proto3.getEnumType(DecisionKind) },
    { no: 10, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Recommendation {
    return new Recommendation().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Recommendation {
    return new Recommendation().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Recommendation {
    return new Recommendation().fromJsonString(jsonString, options);
  }

  static equals(a: Recommendation | PlainMessage<Recommendation> | undefined, b: Recommendation | PlainMessage<Recommendation> | undefined): boolean {
    return proto3.util.equals(Recommendation, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ReviewDecision
 */
export class ReviewDecision extends Message<ReviewDecision> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string recommendation_id = 2;
   */
  recommendationId = "";

  /**
   * @generated from field: int64 recommendation_version = 3;
   */
  recommendationVersion = protoInt64.zero;

  /**
   * @generated from field: clearmind.v1.DecisionKind decision = 4;
   */
  decision = DecisionKind.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp decided_at = 5;
   */
  decidedAt?: Timestamp;

  constructor(data?: PartialMessage<ReviewDecision>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ReviewDecision";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "recommendation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "recommendation_version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "decision", kind: "enum", T: proto3.getEnumType(DecisionKind) },
    { no: 5, name: "decided_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReviewDecision {
    return new ReviewDecision().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReviewDecision {
    return new ReviewDecision().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReviewDecision {
    return new ReviewDecision().fromJsonString(jsonString, options);
  }

  static equals(a: ReviewDecision | PlainMessage<ReviewDecision> | undefined, b: ReviewDecision | PlainMessage<ReviewDecision> | undefined): boolean {
    return proto3.util.equals(ReviewDecision, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListRecommendationsRequest
 */
export class ListRecommendationsRequest extends Message<ListRecommendationsRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  /**
   * @generated from field: repeated clearmind.v1.DecisionKind decisions = 2;
   */
  decisions: DecisionKind[] = [];

  /**
   * @generated from field: clearmind.v1.PageRequest page = 3;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListRecommendationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListRecommendationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "decisions", kind: "enum", T: proto3.getEnumType(DecisionKind), repeated: true },
    { no: 3, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRecommendationsRequest {
    return new ListRecommendationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRecommendationsRequest {
    return new ListRecommendationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRecommendationsRequest {
    return new ListRecommendationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRecommendationsRequest | PlainMessage<ListRecommendationsRequest> | undefined, b: ListRecommendationsRequest | PlainMessage<ListRecommendationsRequest> | undefined): boolean {
    return proto3.util.equals(ListRecommendationsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListRecommendationsResponse
 */
export class ListRecommendationsResponse extends Message<ListRecommendationsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.Recommendation recommendations = 1;
   */
  recommendations: Recommendation[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListRecommendationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListRecommendationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "recommendations", kind: "message", T: Recommendation, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRecommendationsResponse {
    return new ListRecommendationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRecommendationsResponse {
    return new ListRecommendationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRecommendationsResponse {
    return new ListRecommendationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListRecommendationsResponse | PlainMessage<ListRecommendationsResponse> | undefined, b: ListRecommendationsResponse | PlainMessage<ListRecommendationsResponse> | undefined): boolean {
    return proto3.util.equals(ListRecommendationsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.SubmitDecisionRequest
 */
export class SubmitDecisionRequest extends Message<SubmitDecisionRequest> {
  /**
   * @generated from field: string recommendation_id = 1;
   */
  recommendationId = "";

  /**
   * @generated from field: int64 recommendation_version = 2;
   */
  recommendationVersion = protoInt64.zero;

  /**
   * @generated from field: clearmind.v1.DecisionKind decision = 3;
   */
  decision = DecisionKind.UNSPECIFIED;

  constructor(data?: PartialMessage<SubmitDecisionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.SubmitDecisionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "recommendation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "recommendation_version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "decision", kind: "enum", T: proto3.getEnumType(DecisionKind) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitDecisionRequest {
    return new SubmitDecisionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitDecisionRequest {
    return new SubmitDecisionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitDecisionRequest {
    return new SubmitDecisionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitDecisionRequest | PlainMessage<SubmitDecisionRequest> | undefined, b: SubmitDecisionRequest | PlainMessage<SubmitDecisionRequest> | undefined): boolean {
    return proto3.util.equals(SubmitDecisionRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.SubmitDecisionResponse
 */
export class SubmitDecisionResponse extends Message<SubmitDecisionResponse> {
  /**
   * @generated from field: clearmind.v1.ReviewDecision decision = 1;
   */
  decision?: ReviewDecision;

  /**
   * @generated from field: clearmind.v1.Recommendation recommendation = 2;
   */
  recommendation?: Recommendation;

  constructor(data?: PartialMessage<SubmitDecisionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.SubmitDecisionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "decision", kind: "message", T: ReviewDecision },
    { no: 2, name: "recommendation", kind: "message", T: Recommendation },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitDecisionResponse {
    return new SubmitDecisionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitDecisionResponse {
    return new SubmitDecisionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitDecisionResponse {
    return new SubmitDecisionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitDecisionResponse | PlainMessage<SubmitDecisionResponse> | undefined, b: SubmitDecisionResponse | PlainMessage<SubmitDecisionResponse> | undefined): boolean {
    return proto3.util.equals(SubmitDecisionResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListDecisionsRequest
 */
export class ListDecisionsRequest extends Message<ListDecisionsRequest> {
  /**
   * @generated from field: string recommendation_id = 1;
   */
  recommendationId = "";

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId = "";

  /**
   * @generated from field: clearmind.v1.PageRequest page = 3;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListDecisionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListDecisionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "recommendation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDecisionsRequest {
    return new ListDecisionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDecisionsRequest {
    return new ListDecisionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDecisionsRequest {
    return new ListDecisionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListDecisionsRequest | PlainMessage<ListDecisionsRequest> | undefined, b: ListDecisionsRequest | PlainMessage<ListDecisionsRequest> | undefined): boolean {
    return proto3.util.equals(ListDecisionsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListDecisionsResponse
 */
export class ListDecisionsResponse extends Message<ListDecisionsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.ReviewDecision decisions = 1;
   */
  decisions: ReviewDecision[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListDecisionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListDecisionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "decisions", kind: "message", T: ReviewDecision, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDecisionsResponse {
    return new ListDecisionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDecisionsResponse {
    return new ListDecisionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDecisionsResponse {
    return new ListDecisionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListDecisionsResponse | PlainMessage<ListDecisionsResponse> | undefined, b: ListDecisionsResponse | PlainMessage<ListDecisionsResponse> | undefined): boolean {
    return proto3.util.equals(ListDecisionsResponse, a, b);
  }
}

