// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file clearmind/v1/subscription.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSnapshotRequest, CreateSnapshotResponse, GetSnapshotRequest, GetSnapshotResponse, ImportSubscriptionsRequest, ImportSubscriptionsResponse, ListSnapshotsRequest, ListSnapshotsResponse, ListSubscriptionsRequest, ListSubscriptionsResponse } from "./subscription_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service clearmind.v1.SubscriptionService
 */
export const SubscriptionService = {
  typeName: "clearmind.v1.SubscriptionService",
  methods: {
    /**
     * @generated from rpc clearmind.v1.SubscriptionService.ImportSubscriptions
     */
    importSubscriptions: {
      name: "ImportSubscriptions",
      I: ImportSubscriptionsRequest,
      O: ImportSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.SubscriptionService.ListSubscriptions
     */
    listSubscriptions: {
      name: "ListSubscriptions",
      I: ListSubscriptionsRequest,
      O: ListSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.SubscriptionService.CreateSnapshot
     */
    createSnapshot: {
      name: "CreateSnapshot",
      I: CreateSnapshotRequest,
      O: CreateSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.SubscriptionService.ListSnapshots
     */
    listSnapshots: {
      name: "ListSnapshots",
      I: ListSnapshotsRequest,
      O: ListSnapshotsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc clearmind.v1.SubscriptionService.GetSnapshot
     */
    getSnapshot: {
      name: "GetSnapshot",
      I: GetSnapshotRequest,
      O: GetSnapshotResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

