// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file clearmind/v1/subscription.proto (package clearmind.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { PageRequest, PageResponse, SocialMediaType } from "./common_pb.js";

/**
 * @generated from enum clearmind.v1.SubscriptionKind
 */
export enum SubscriptionKind {
  /**
   * @generated from enum value: SUBSCRIPTION_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUBSCRIPTION_KIND_CHANNEL = 1;
   */
  CHANNEL = 1,

  /**
   * @generated from enum value: SUBSCRIPTION_KIND_GROUP = 2;
   */
  GROUP = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(SubscriptionKind)
proto3.util.setEnumType(SubscriptionKind, "clearmind.v1.SubscriptionKind", [
  { no: 0, name: "SUBSCRIPTION_KIND_UNSPECIFIED" },
  { no: 1, name: "SUBSCRIPTION_KIND_CHANNEL" },
  { no: 2, name: "SUBSCRIPTION_KIND_GROUP" },
]);

/**
 * @generated from enum clearmind.v1.SubscriptionVisibility
 */
export enum SubscriptionVisibility {
  /**
   * @generated from enum value: SUBSCRIPTION_VISIBILITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SUBSCRIPTION_VISIBILITY_PUBLIC = 1;
   */
  PUBLIC = 1,

  /**
   * @generated from enum value: SUBSCRIPTION_VISIBILITY_PRIVATE = 2;
   */
  PRIVATE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(SubscriptionVisibility)
proto3.util.setEnumType(SubscriptionVisibility, "clearmind.v1.SubscriptionVisibility", [
  { no: 0, name: "SUBSCRIPTION_VISIBILITY_UNSPECIFIED" },
  { no: 1, name: "SUBSCRIPTION_VISIBILITY_PUBLIC" },
  { no: 2, name: "SUBSCRIPTION_VISIBILITY_PRIVATE" },
]);

/**
 * @generated from message clearmind.v1.Subscription
 */
export class Subscription extends Message<Subscription> {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * @generated from field: clearmind.v1.SocialMediaType social_media_type = 8;
   */
  socialMediaType = SocialMediaType.UNSPECIFIED;

  /**
   * @generated from field: string foreign_id = 9;
   */
  foreignId = "";

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string username = 3;
   */
  username = "";

  /**
   * @generated from field: clearmind.v1.SubscriptionKind kind = 4;
   */
  kind = SubscriptionKind.UNSPECIFIED;

  /**
   * @generated from field: clearmind.v1.SubscriptionVisibility visibility = 5;
   */
  visibility = SubscriptionVisibility.UNSPECIFIED;

  /**
   * @generated from field: bool is_importable = 6;
   */
  isImportable = false;

  /**
   * @generated from field: google.protobuf.Timestamp imported_at = 7;
   */
  importedAt?: Timestamp;

  constructor(data?: PartialMessage<Subscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.Subscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "social_media_type", kind: "enum", T: proto3.getEnumType(SocialMediaType) },
    { no: 9, name: "foreign_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "kind", kind: "enum", T: proto3.getEnumType(SubscriptionKind) },
    { no: 5, name: "visibility", kind: "enum", T: proto3.getEnumType(SubscriptionVisibility) },
    { no: 6, name: "is_importable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "imported_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Subscription {
    return new Subscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Subscription {
    return new Subscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Subscription {
    return new Subscription().fromJsonString(jsonString, options);
  }

  static equals(a: Subscription | PlainMessage<Subscription> | undefined, b: Subscription | PlainMessage<Subscription> | undefined): boolean {
    return proto3.util.equals(Subscription, a, b);
  }
}

/**
 * @generated from message clearmind.v1.SubscriptionSnapshot
 */
export class SubscriptionSnapshot extends Message<SubscriptionSnapshot> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: int64 version = 2;
   */
  version = protoInt64.zero;

  /**
   * @generated from field: google.protobuf.Timestamp frozen_at = 3;
   */
  frozenAt?: Timestamp;

  /**
   * @generated from field: int32 member_count = 4;
   */
  memberCount = 0;

  constructor(data?: PartialMessage<SubscriptionSnapshot>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.SubscriptionSnapshot";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "frozen_at", kind: "message", T: Timestamp },
    { no: 4, name: "member_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscriptionSnapshot {
    return new SubscriptionSnapshot().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscriptionSnapshot {
    return new SubscriptionSnapshot().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscriptionSnapshot {
    return new SubscriptionSnapshot().fromJsonString(jsonString, options);
  }

  static equals(a: SubscriptionSnapshot | PlainMessage<SubscriptionSnapshot> | undefined, b: SubscriptionSnapshot | PlainMessage<SubscriptionSnapshot> | undefined): boolean {
    return proto3.util.equals(SubscriptionSnapshot, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ImportSubscriptionsRequest
 */
export class ImportSubscriptionsRequest extends Message<ImportSubscriptionsRequest> {
  /**
   * @generated from field: bytes export_file = 1;
   */
  exportFile = new Uint8Array(0);

  constructor(data?: PartialMessage<ImportSubscriptionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ImportSubscriptionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "export_file", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportSubscriptionsRequest {
    return new ImportSubscriptionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportSubscriptionsRequest {
    return new ImportSubscriptionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportSubscriptionsRequest {
    return new ImportSubscriptionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ImportSubscriptionsRequest | PlainMessage<ImportSubscriptionsRequest> | undefined, b: ImportSubscriptionsRequest | PlainMessage<ImportSubscriptionsRequest> | undefined): boolean {
    return proto3.util.equals(ImportSubscriptionsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ImportSubscriptionsResponse
 */
export class ImportSubscriptionsResponse extends Message<ImportSubscriptionsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.Subscription subscriptions = 1;
   */
  subscriptions: Subscription[] = [];

  /**
   * @generated from field: int32 importable_count = 2;
   */
  importableCount = 0;

  constructor(data?: PartialMessage<ImportSubscriptionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ImportSubscriptionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscriptions", kind: "message", T: Subscription, repeated: true },
    { no: 2, name: "importable_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportSubscriptionsResponse {
    return new ImportSubscriptionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportSubscriptionsResponse {
    return new ImportSubscriptionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportSubscriptionsResponse {
    return new ImportSubscriptionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ImportSubscriptionsResponse | PlainMessage<ImportSubscriptionsResponse> | undefined, b: ImportSubscriptionsResponse | PlainMessage<ImportSubscriptionsResponse> | undefined): boolean {
    return proto3.util.equals(ImportSubscriptionsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListSubscriptionsRequest
 */
export class ListSubscriptionsRequest extends Message<ListSubscriptionsRequest> {
  /**
   * @generated from field: clearmind.v1.PageRequest page = 1;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListSubscriptionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListSubscriptionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSubscriptionsRequest {
    return new ListSubscriptionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSubscriptionsRequest {
    return new ListSubscriptionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSubscriptionsRequest {
    return new ListSubscriptionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListSubscriptionsRequest | PlainMessage<ListSubscriptionsRequest> | undefined, b: ListSubscriptionsRequest | PlainMessage<ListSubscriptionsRequest> | undefined): boolean {
    return proto3.util.equals(ListSubscriptionsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListSubscriptionsResponse
 */
export class ListSubscriptionsResponse extends Message<ListSubscriptionsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.Subscription subscriptions = 1;
   */
  subscriptions: Subscription[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListSubscriptionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListSubscriptionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscriptions", kind: "message", T: Subscription, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSubscriptionsResponse {
    return new ListSubscriptionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSubscriptionsResponse {
    return new ListSubscriptionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSubscriptionsResponse {
    return new ListSubscriptionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListSubscriptionsResponse | PlainMessage<ListSubscriptionsResponse> | undefined, b: ListSubscriptionsResponse | PlainMessage<ListSubscriptionsResponse> | undefined): boolean {
    return proto3.util.equals(ListSubscriptionsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.CreateSnapshotRequest
 */
export class CreateSnapshotRequest extends Message<CreateSnapshotRequest> {
  /**
   * @generated from field: repeated string member_channel_ids = 1;
   */
  memberChannelIds: string[] = [];

  constructor(data?: PartialMessage<CreateSnapshotRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.CreateSnapshotRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "member_channel_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSnapshotRequest {
    return new CreateSnapshotRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSnapshotRequest {
    return new CreateSnapshotRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSnapshotRequest {
    return new CreateSnapshotRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateSnapshotRequest | PlainMessage<CreateSnapshotRequest> | undefined, b: CreateSnapshotRequest | PlainMessage<CreateSnapshotRequest> | undefined): boolean {
    return proto3.util.equals(CreateSnapshotRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.CreateSnapshotResponse
 */
export class CreateSnapshotResponse extends Message<CreateSnapshotResponse> {
  /**
   * @generated from field: clearmind.v1.SubscriptionSnapshot snapshot = 1;
   */
  snapshot?: SubscriptionSnapshot;

  constructor(data?: PartialMessage<CreateSnapshotResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.CreateSnapshotResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot", kind: "message", T: SubscriptionSnapshot },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSnapshotResponse {
    return new CreateSnapshotResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSnapshotResponse {
    return new CreateSnapshotResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSnapshotResponse {
    return new CreateSnapshotResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateSnapshotResponse | PlainMessage<CreateSnapshotResponse> | undefined, b: CreateSnapshotResponse | PlainMessage<CreateSnapshotResponse> | undefined): boolean {
    return proto3.util.equals(CreateSnapshotResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListSnapshotsRequest
 */
export class ListSnapshotsRequest extends Message<ListSnapshotsRequest> {
  /**
   * @generated from field: clearmind.v1.PageRequest page = 1;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListSnapshotsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListSnapshotsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSnapshotsRequest {
    return new ListSnapshotsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSnapshotsRequest {
    return new ListSnapshotsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSnapshotsRequest {
    return new ListSnapshotsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListSnapshotsRequest | PlainMessage<ListSnapshotsRequest> | undefined, b: ListSnapshotsRequest | PlainMessage<ListSnapshotsRequest> | undefined): boolean {
    return proto3.util.equals(ListSnapshotsRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.ListSnapshotsResponse
 */
export class ListSnapshotsResponse extends Message<ListSnapshotsResponse> {
  /**
   * @generated from field: repeated clearmind.v1.SubscriptionSnapshot snapshots = 1;
   */
  snapshots: SubscriptionSnapshot[] = [];

  /**
   * @generated from field: clearmind.v1.PageResponse page = 2;
   */
  page?: PageResponse;

  constructor(data?: PartialMessage<ListSnapshotsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.ListSnapshotsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshots", kind: "message", T: SubscriptionSnapshot, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSnapshotsResponse {
    return new ListSnapshotsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSnapshotsResponse {
    return new ListSnapshotsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSnapshotsResponse {
    return new ListSnapshotsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListSnapshotsResponse | PlainMessage<ListSnapshotsResponse> | undefined, b: ListSnapshotsResponse | PlainMessage<ListSnapshotsResponse> | undefined): boolean {
    return proto3.util.equals(ListSnapshotsResponse, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetSnapshotRequest
 */
export class GetSnapshotRequest extends Message<GetSnapshotRequest> {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId = "";

  constructor(data?: PartialMessage<GetSnapshotRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetSnapshotRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSnapshotRequest {
    return new GetSnapshotRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSnapshotRequest {
    return new GetSnapshotRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSnapshotRequest {
    return new GetSnapshotRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSnapshotRequest | PlainMessage<GetSnapshotRequest> | undefined, b: GetSnapshotRequest | PlainMessage<GetSnapshotRequest> | undefined): boolean {
    return proto3.util.equals(GetSnapshotRequest, a, b);
  }
}

/**
 * @generated from message clearmind.v1.GetSnapshotResponse
 */
export class GetSnapshotResponse extends Message<GetSnapshotResponse> {
  /**
   * @generated from field: clearmind.v1.SubscriptionSnapshot snapshot = 1;
   */
  snapshot?: SubscriptionSnapshot;

  /**
   * @generated from field: repeated clearmind.v1.Subscription members = 2;
   */
  members: Subscription[] = [];

  constructor(data?: PartialMessage<GetSnapshotResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "clearmind.v1.GetSnapshotResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "snapshot", kind: "message", T: SubscriptionSnapshot },
    { no: 2, name: "members", kind: "message", T: Subscription, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSnapshotResponse {
    return new GetSnapshotResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSnapshotResponse {
    return new GetSnapshotResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSnapshotResponse {
    return new GetSnapshotResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSnapshotResponse | PlainMessage<GetSnapshotResponse> | undefined, b: GetSnapshotResponse | PlainMessage<GetSnapshotResponse> | undefined): boolean {
    return proto3.util.equals(GetSnapshotResponse, a, b);
  }
}

